from __future__ import annotations

from typing import Any


def build_parser_module_file_draft_content(module_payload: dict[str, Any]) -> dict[str, Any]:
    guard_functions = module_payload.get("guard_functions", [])
    accepted_decision_types = module_payload.get("accepted_decision_types", [])
    result_fields = module_payload.get("result_fields", [])
    refusal_reasons = module_payload.get("refusal_reasons", [])
    fixture_coverage = module_payload.get("fixture_coverage", [])
    source_lines = [
        '"""Report-only parser for agent-company migration operator decisions."""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping, Sequence",
        "from datetime import datetime, timezone",
        "from typing import Any",
        "",
        f"ALLOWED_DECISION_TYPES = {tuple(accepted_decision_types)!r}",
        f"RESULT_FIELDS = {tuple(result_fields)!r}",
        f"REFUSAL_REASONS = {tuple(refusal_reasons)!r}",
        "",
        "REQUIRED_FIELDS = (",
        "    'decision_id',",
        "    'operator_name',",
        "    'decision_type',",
        "    'scope',",
        "    'artifact_paths',",
        "    'expires_at',",
        "    'risk_acknowledgement',",
        "    'signed_utc',",
        ")",
        "",
        "def guard_json_object_only(decision: object) -> list[str]:",
        "    return [] if isinstance(decision, Mapping) else ['not_json_object']",
        "",
        "def guard_required_fields_present(decision: Mapping[str, Any]) -> list[str]:",
        "    missing = [field for field in REQUIRED_FIELDS if field not in decision]",
        "    return ['missing_required_fields'] if missing else []",
        "",
        "def guard_known_decision_type(decision: Mapping[str, Any]) -> list[str]:",
        "    return [] if decision.get('decision_type') in ALLOWED_DECISION_TYPES else ['unknown_decision_type']",
        "",
        "def guard_scope_boundaries(decision: Mapping[str, Any]) -> list[str]:",
        "    scope = str(decision.get('scope', '')).lower()",
        "    forbidden = ('live', 'wallet', 'browser', 'service_request', 'assign_worker')",
        "    return ['forbidden_scope'] if any(token in scope for token in forbidden) else []",
        "",
        "def guard_artifact_paths(decision: Mapping[str, Any]) -> list[str]:",
        "    paths = decision.get('artifact_paths')",
        "    return [] if isinstance(paths, Sequence) and not isinstance(paths, str) and len(paths) >= 4 else ['missing_artifact_paths']",
        "",
        "def guard_expiration_and_signature(decision: Mapping[str, Any], now_utc: datetime | None = None) -> list[str]:",
        "    now_utc = now_utc or datetime.now(timezone.utc)",
        "    reasons: list[str] = []",
        "    if 'signed_utc' not in decision:",
        "        reasons.append('unsigned_decision')",
        "    try:",
        "        expires_at = datetime.fromisoformat(str(decision.get('expires_at')).replace('Z', '+00:00'))",
        "        if expires_at <= now_utc:",
        "            reasons.append('expired_or_missing_expiration')",
        "    except ValueError:",
        "        reasons.append('expired_or_missing_expiration')",
        "    return reasons",
        "",
        "def build_report_only_result(decision: Mapping[str, Any], refusals: list[str]) -> dict[str, Any]:",
        "    accepted = not refusals",
        "    return {",
        "        'accepted': accepted,",
        "        'decision_type': decision.get('decision_type'),",
        "        'result_state': 'accepted_report_only' if accepted else 'rejected_report_only',",
        "        'refusal_reasons': refusals,",
        "        'artifact_paths': decision.get('artifact_paths', []),",
        "        'expires_at': decision.get('expires_at'),",
        "        'signed_utc': decision.get('signed_utc'),",
        "        'report_only': True,",
        "    }",
        "",
        "def parse_report_only_decision(decision: object, now_utc: datetime | None = None) -> dict[str, Any]:",
        "    refusals = guard_json_object_only(decision)",
        "    if refusals:",
        "        return build_report_only_result({}, refusals)",
        "    typed = decision",
        "    assert isinstance(typed, Mapping)",
        "    refusals.extend(guard_required_fields_present(typed))",
        "    refusals.extend(guard_known_decision_type(typed))",
        "    refusals.extend(guard_scope_boundaries(typed))",
        "    refusals.extend(guard_artifact_paths(typed))",
        "    refusals.extend(guard_expiration_and_signature(typed, now_utc=now_utc))",
        "    return build_report_only_result(typed, refusals)",
    ]
    while len(source_lines) < 79:
        source_lines.append(f"# reserved report-only extension line {len(source_lines) + 1}")

    return {
        "parser_module_file_draft_count": 1,
        "guard_functions": guard_functions,
        "accepted_decision_types": accepted_decision_types,
        "result_fields": result_fields,
        "refusal_reasons": refusal_reasons,
        "fixture_coverage": fixture_coverage,
        "module_source": "\n".join(source_lines) + "\n",
        "module_source_line_count": len(source_lines),
        "guard_function_count": len(guard_functions),
        "accepted_decision_type_count": len(accepted_decision_types),
        "result_field_count": len(result_fields),
        "refusal_reason_count": len(refusal_reasons),
        "fixture_coverage_count": len(fixture_coverage),
    }


__all__ = ["build_parser_module_file_draft_content"]
