"""Digital-products report path constants for Agent Company."""

from __future__ import annotations

from .paths import REPORTS_DIR

DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_REPORT = REPORTS_DIR / "digital-products-local-demand-proof-latest.md"
DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_JSON = REPORTS_DIR / "digital-products-local-demand-proof-latest.json"
DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-demand-proof-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_REPORT = REPORTS_DIR / "digital-products-local-demand-memo-latest.md"
DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_JSON = REPORTS_DIR / "digital-products-local-demand-memo-latest.json"
DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-demand-memo-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_REPORT = REPORTS_DIR / "digital-products-local-build-brief-latest.md"
DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_JSON = REPORTS_DIR / "digital-products-local-build-brief-latest.json"
DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-build-brief-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_REPORT = REPORTS_DIR / "digital-products-local-asset-outline-latest.md"
DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_JSON = REPORTS_DIR / "digital-products-local-asset-outline-latest.json"
DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-asset-outline-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_REPORT = REPORTS_DIR / "digital-products-local-asset-draft-latest.md"
DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_JSON = REPORTS_DIR / "digital-products-local-asset-draft-latest.json"
DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-asset-draft-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_REPORT = REPORTS_DIR / "digital-products-local-quality-pass-latest.md"
DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_JSON = REPORTS_DIR / "digital-products-local-quality-pass-latest.json"
DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-quality-pass-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_REPORT = REPORTS_DIR / "digital-products-local-packaging-manifest-latest.md"
DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_JSON = REPORTS_DIR / "digital-products-local-packaging-manifest-latest.json"
DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-packaging-manifest-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_REPORT = REPORTS_DIR / "digital-products-local-package-files-latest.md"
DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_JSON = REPORTS_DIR / "digital-products-local-package-files-latest.json"
DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-package-files-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_REPORT = REPORTS_DIR / "digital-products-local-completeness-check-latest.md"
DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_JSON = REPORTS_DIR / "digital-products-local-completeness-check-latest.json"
DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-completeness-check-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_REPORT = REPORTS_DIR / "digital-products-local-private-review-packet-latest.md"
DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_JSON = REPORTS_DIR / "digital-products-local-private-review-packet-latest.json"
DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-private-review-packet-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_REPORT = REPORTS_DIR / "digital-products-local-private-review-decision-latest.md"
DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_JSON = REPORTS_DIR / "digital-products-local-private-review-decision-latest.json"
DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-private-review-decision-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_REPORT = REPORTS_DIR / "digital-products-local-revision-pass-latest.md"
DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_JSON = REPORTS_DIR / "digital-products-local-revision-pass-latest.json"
DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-revision-pass-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_REPORT = REPORTS_DIR / "digital-products-local-revised-completeness-latest.md"
DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_JSON = REPORTS_DIR / "digital-products-local-revised-completeness-latest.json"
DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-revised-completeness-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_REPORT = REPORTS_DIR / "digital-products-local-gate-decision-packet-latest.md"
DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_JSON = REPORTS_DIR / "digital-products-local-gate-decision-packet-latest.json"
DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-gate-decision-packet-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_REPORT = REPORTS_DIR / "digital-products-local-gate-choice-latest.md"
DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_JSON = REPORTS_DIR / "digital-products-local-gate-choice-latest.json"
DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-gate-choice-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_REPORT = REPORTS_DIR / "digital-products-local-copy-polish-latest.md"
DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_JSON = REPORTS_DIR / "digital-products-local-copy-polish-latest.json"
DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-copy-polish-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_REPORT = REPORTS_DIR / "digital-products-local-post-polish-readiness-latest.md"
DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_JSON = REPORTS_DIR / "digital-products-local-post-polish-readiness-latest.json"
DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-post-polish-readiness-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_REPORT = REPORTS_DIR / "digital-products-local-approval-request-drafts-latest.md"
DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_JSON = REPORTS_DIR / "digital-products-local-approval-request-drafts-latest.json"
DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-approval-request-drafts-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_REPORT = REPORTS_DIR / "digital-products-local-operator-approval-brief-latest.md"
DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_JSON = REPORTS_DIR / "digital-products-local-operator-approval-brief-latest.json"
DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-operator-approval-brief-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_REPORT = REPORTS_DIR / "digital-products-local-post-approval-simulation-plan-latest.md"
DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_JSON = REPORTS_DIR / "digital-products-local-post-approval-simulation-plan-latest.json"
DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-post-approval-simulation-plan-validation-latest.json"
DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_REPORT = REPORTS_DIR / "digital-products-local-gated-hold-register-latest.md"
DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_JSON = REPORTS_DIR / "digital-products-local-gated-hold-register-latest.json"
DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_VALIDATION_JSON = REPORTS_DIR / "digital-products-local-gated-hold-register-validation-latest.json"

__all__ = [
    "DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_JSON",
    "DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_JSON",
    "DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_JSON",
    "DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_JSON",
    "DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_JSON",
    "DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_JSON",
    "DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_JSON",
    "DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_JSON",
    "DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_JSON",
    "DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_JSON",
    "DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_JSON",
    "DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_JSON",
    "DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_JSON",
    "DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_JSON",
    "DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_JSON",
    "DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_JSON",
    "DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_JSON",
    "DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_JSON",
    "DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_JSON",
    "DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_VALIDATION_JSON",
    "DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_REPORT",
    "DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_JSON",
    "DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_VALIDATION_JSON",
]
