"""Service-worker report path constants for Agent Company."""

from __future__ import annotations

from .paths import REPORTS_DIR

SERVICE_WORKER_REQUEST_QUEUE_REPORT = REPORTS_DIR / "service-worker-request-queue-latest.md"
SERVICE_WORKER_REQUEST_QUEUE_JSON = REPORTS_DIR / "service-worker-request-queue-latest.json"
SERVICE_WORKER_REQUEST_QUEUE_VALIDATION_JSON = REPORTS_DIR / "service-worker-request-queue-validation-latest.json"
SERVICE_WORKER_DEQUEUE_REPORT = REPORTS_DIR / "service-worker-dequeue-plan-latest.md"
SERVICE_WORKER_DEQUEUE_JSON = REPORTS_DIR / "service-worker-dequeue-plan-latest.json"
SERVICE_WORKER_DEQUEUE_VALIDATION_JSON = REPORTS_DIR / "service-worker-dequeue-plan-validation-latest.json"
SERVICE_WORKER_DEQUEUE_RESULT_DIR = REPORTS_DIR / "service-worker-dequeue-results"
SERVICE_WORKER_READINESS_REPORT = REPORTS_DIR / "service-worker-execution-readiness-latest.md"
SERVICE_WORKER_READINESS_JSON = REPORTS_DIR / "service-worker-execution-readiness-latest.json"
SERVICE_WORKER_READINESS_VALIDATION_JSON = REPORTS_DIR / "service-worker-execution-readiness-validation-latest.json"
SERVICE_WORKER_SCOPE_DIFF_REPORT = REPORTS_DIR / "service-worker-approval-scope-diff-latest.md"
SERVICE_WORKER_SCOPE_DIFF_JSON = REPORTS_DIR / "service-worker-approval-scope-diff-latest.json"
SERVICE_WORKER_SCOPE_DIFF_VALIDATION_JSON = REPORTS_DIR / "service-worker-approval-scope-diff-validation-latest.json"
SERVICE_WORKER_SCOPE_TEMPLATE_REPORT = REPORTS_DIR / "service-worker-exact-scope-templates-latest.md"
SERVICE_WORKER_SCOPE_TEMPLATE_JSON = REPORTS_DIR / "service-worker-exact-scope-templates-latest.json"
SERVICE_WORKER_SCOPE_TEMPLATE_VALIDATION_JSON = REPORTS_DIR / "service-worker-exact-scope-templates-validation-latest.json"
SERVICE_WORKER_APPROVAL_REVIEW_REPORT = REPORTS_DIR / "service-worker-cro-approval-review-latest.md"
SERVICE_WORKER_APPROVAL_REVIEW_JSON = REPORTS_DIR / "service-worker-cro-approval-review-latest.json"
SERVICE_WORKER_APPROVAL_REVIEW_VALIDATION_JSON = REPORTS_DIR / "service-worker-cro-approval-review-validation-latest.json"
SERVICE_WORKER_ASSIGNMENT_PLAN_REPORT = REPORTS_DIR / "service-worker-assignment-plan-latest.md"
SERVICE_WORKER_ASSIGNMENT_PLAN_JSON = REPORTS_DIR / "service-worker-assignment-plan-latest.json"
SERVICE_WORKER_ASSIGNMENT_PLAN_VALIDATION_JSON = REPORTS_DIR / "service-worker-assignment-plan-validation-latest.json"
SERVICE_WORKER_POOL_REGISTRY_REPORT = REPORTS_DIR / "service-worker-pool-registry-latest.md"
SERVICE_WORKER_POOL_REGISTRY_JSON = REPORTS_DIR / "service-worker-pool-registry-latest.json"
SERVICE_WORKER_POOL_REGISTRY_VALIDATION_JSON = REPORTS_DIR / "service-worker-pool-registry-validation-latest.json"
SERVICE_WORKER_POOL_REGISTRATION_REPORT = REPORTS_DIR / "service-worker-pool-registration-plan-latest.md"
SERVICE_WORKER_POOL_REGISTRATION_JSON = REPORTS_DIR / "service-worker-pool-registration-plan-latest.json"
SERVICE_WORKER_POOL_REGISTRATION_VALIDATION_JSON = REPORTS_DIR / "service-worker-pool-registration-plan-validation-latest.json"
SERVICE_WORKER_GATE_MAP_REPORT = REPORTS_DIR / "service-worker-gate-map-latest.md"
SERVICE_WORKER_GATE_MAP_JSON = REPORTS_DIR / "service-worker-gate-map-latest.json"
SERVICE_WORKER_GATE_MAP_VALIDATION_JSON = REPORTS_DIR / "service-worker-gate-map-validation-latest.json"
SERVICE_WORKER_CHAIN_INTEGRITY_REPORT = REPORTS_DIR / "service-worker-chain-integrity-latest.md"
SERVICE_WORKER_CHAIN_INTEGRITY_JSON = REPORTS_DIR / "service-worker-chain-integrity-latest.json"
SERVICE_WORKER_CHAIN_INTEGRITY_VALIDATION_JSON = REPORTS_DIR / "service-worker-chain-integrity-validation-latest.json"
SERVICE_WORKER_HUMAN_DECISION_PACKET_DIR = REPORTS_DIR / "service-worker-human-decision-packets"
SERVICE_WORKER_HUMAN_DECISION_PACKETS_REPORT = REPORTS_DIR / "service-worker-human-decision-packets-latest.md"
SERVICE_WORKER_HUMAN_DECISION_PACKETS_JSON = REPORTS_DIR / "service-worker-human-decision-packets-latest.json"
SERVICE_WORKER_HUMAN_DECISION_PACKETS_VALIDATION_JSON = REPORTS_DIR / "service-worker-human-decision-packets-validation-latest.json"
SERVICE_WORKER_POST_DECISION_SIMULATION_REPORT = REPORTS_DIR / "service-worker-post-decision-simulation-latest.md"
SERVICE_WORKER_POST_DECISION_SIMULATION_JSON = REPORTS_DIR / "service-worker-post-decision-simulation-latest.json"
SERVICE_WORKER_POST_DECISION_SIMULATION_VALIDATION_JSON = REPORTS_DIR / "service-worker-post-decision-simulation-validation-latest.json"
SERVICE_WORKER_POST_DECISION_REFRESH_PLAN_REPORT = REPORTS_DIR / "service-worker-post-decision-refresh-plan-latest.md"
SERVICE_WORKER_POST_DECISION_REFRESH_PLAN_JSON = REPORTS_DIR / "service-worker-post-decision-refresh-plan-latest.json"
SERVICE_WORKER_POST_DECISION_REFRESH_PLAN_VALIDATION_JSON = REPORTS_DIR / "service-worker-post-decision-refresh-plan-validation-latest.json"
SERVICE_WORKER_DECISION_DRIFT_REPORT = REPORTS_DIR / "service-worker-decision-drift-guard-latest.md"
SERVICE_WORKER_DECISION_DRIFT_JSON = REPORTS_DIR / "service-worker-decision-drift-guard-latest.json"
SERVICE_WORKER_DECISION_DRIFT_VALIDATION_JSON = REPORTS_DIR / "service-worker-decision-drift-guard-validation-latest.json"
SERVICE_WORKER_DECISION_COMMAND_SAFETY_REPORT = REPORTS_DIR / "service-worker-decision-command-safety-latest.md"
SERVICE_WORKER_DECISION_COMMAND_SAFETY_JSON = REPORTS_DIR / "service-worker-decision-command-safety-latest.json"
SERVICE_WORKER_DECISION_COMMAND_SAFETY_VALIDATION_JSON = REPORTS_DIR / "service-worker-decision-command-safety-validation-latest.json"
SERVICE_WORKER_DECISION_AUTHORITY_MATRIX_REPORT = REPORTS_DIR / "service-worker-decision-authority-matrix-latest.md"
SERVICE_WORKER_DECISION_AUTHORITY_MATRIX_JSON = REPORTS_DIR / "service-worker-decision-authority-matrix-latest.json"
SERVICE_WORKER_DECISION_AUTHORITY_MATRIX_VALIDATION_JSON = REPORTS_DIR / "service-worker-decision-authority-matrix-validation-latest.json"
SERVICE_WORKER_DECISION_PREFLIGHT_REPORT = REPORTS_DIR / "service-worker-decision-preflight-latest.md"
SERVICE_WORKER_DECISION_PREFLIGHT_JSON = REPORTS_DIR / "service-worker-decision-preflight-latest.json"
SERVICE_WORKER_DECISION_PREFLIGHT_VALIDATION_JSON = REPORTS_DIR / "service-worker-decision-preflight-validation-latest.json"

__all__ = [
    "SERVICE_WORKER_REQUEST_QUEUE_REPORT",
    "SERVICE_WORKER_REQUEST_QUEUE_JSON",
    "SERVICE_WORKER_REQUEST_QUEUE_VALIDATION_JSON",
    "SERVICE_WORKER_DEQUEUE_REPORT",
    "SERVICE_WORKER_DEQUEUE_JSON",
    "SERVICE_WORKER_DEQUEUE_VALIDATION_JSON",
    "SERVICE_WORKER_DEQUEUE_RESULT_DIR",
    "SERVICE_WORKER_READINESS_REPORT",
    "SERVICE_WORKER_READINESS_JSON",
    "SERVICE_WORKER_READINESS_VALIDATION_JSON",
    "SERVICE_WORKER_SCOPE_DIFF_REPORT",
    "SERVICE_WORKER_SCOPE_DIFF_JSON",
    "SERVICE_WORKER_SCOPE_DIFF_VALIDATION_JSON",
    "SERVICE_WORKER_SCOPE_TEMPLATE_REPORT",
    "SERVICE_WORKER_SCOPE_TEMPLATE_JSON",
    "SERVICE_WORKER_SCOPE_TEMPLATE_VALIDATION_JSON",
    "SERVICE_WORKER_APPROVAL_REVIEW_REPORT",
    "SERVICE_WORKER_APPROVAL_REVIEW_JSON",
    "SERVICE_WORKER_APPROVAL_REVIEW_VALIDATION_JSON",
    "SERVICE_WORKER_ASSIGNMENT_PLAN_REPORT",
    "SERVICE_WORKER_ASSIGNMENT_PLAN_JSON",
    "SERVICE_WORKER_ASSIGNMENT_PLAN_VALIDATION_JSON",
    "SERVICE_WORKER_POOL_REGISTRY_REPORT",
    "SERVICE_WORKER_POOL_REGISTRY_JSON",
    "SERVICE_WORKER_POOL_REGISTRY_VALIDATION_JSON",
    "SERVICE_WORKER_POOL_REGISTRATION_REPORT",
    "SERVICE_WORKER_POOL_REGISTRATION_JSON",
    "SERVICE_WORKER_POOL_REGISTRATION_VALIDATION_JSON",
    "SERVICE_WORKER_GATE_MAP_REPORT",
    "SERVICE_WORKER_GATE_MAP_JSON",
    "SERVICE_WORKER_GATE_MAP_VALIDATION_JSON",
    "SERVICE_WORKER_CHAIN_INTEGRITY_REPORT",
    "SERVICE_WORKER_CHAIN_INTEGRITY_JSON",
    "SERVICE_WORKER_CHAIN_INTEGRITY_VALIDATION_JSON",
    "SERVICE_WORKER_HUMAN_DECISION_PACKET_DIR",
    "SERVICE_WORKER_HUMAN_DECISION_PACKETS_REPORT",
    "SERVICE_WORKER_HUMAN_DECISION_PACKETS_JSON",
    "SERVICE_WORKER_HUMAN_DECISION_PACKETS_VALIDATION_JSON",
    "SERVICE_WORKER_POST_DECISION_SIMULATION_REPORT",
    "SERVICE_WORKER_POST_DECISION_SIMULATION_JSON",
    "SERVICE_WORKER_POST_DECISION_SIMULATION_VALIDATION_JSON",
    "SERVICE_WORKER_POST_DECISION_REFRESH_PLAN_REPORT",
    "SERVICE_WORKER_POST_DECISION_REFRESH_PLAN_JSON",
    "SERVICE_WORKER_POST_DECISION_REFRESH_PLAN_VALIDATION_JSON",
    "SERVICE_WORKER_DECISION_DRIFT_REPORT",
    "SERVICE_WORKER_DECISION_DRIFT_JSON",
    "SERVICE_WORKER_DECISION_DRIFT_VALIDATION_JSON",
    "SERVICE_WORKER_DECISION_COMMAND_SAFETY_REPORT",
    "SERVICE_WORKER_DECISION_COMMAND_SAFETY_JSON",
    "SERVICE_WORKER_DECISION_COMMAND_SAFETY_VALIDATION_JSON",
    "SERVICE_WORKER_DECISION_AUTHORITY_MATRIX_REPORT",
    "SERVICE_WORKER_DECISION_AUTHORITY_MATRIX_JSON",
    "SERVICE_WORKER_DECISION_AUTHORITY_MATRIX_VALIDATION_JSON",
    "SERVICE_WORKER_DECISION_PREFLIGHT_REPORT",
    "SERVICE_WORKER_DECISION_PREFLIGHT_JSON",
    "SERVICE_WORKER_DECISION_PREFLIGHT_VALIDATION_JSON",
]
