"""Agent Company migration report path constants."""

from __future__ import annotations

from .paths import REPORTS_DIR

AGENT_COMPANY_INFRASTRUCTURE_RADAR_REPORT = REPORTS_DIR / "agent-company-infrastructure-radar-latest.md"
AGENT_COMPANY_INFRASTRUCTURE_RADAR_JSON = REPORTS_DIR / "agent-company-infrastructure-radar-latest.json"
AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON = REPORTS_DIR / "agent-company-infrastructure-radar-validation-latest.json"
AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_REPORT = REPORTS_DIR / "agent-company-department-architecture-packet-latest.md"
AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_JSON = REPORTS_DIR / "agent-company-department-architecture-packet-latest.json"
AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON = REPORTS_DIR / "agent-company-department-architecture-packet-validation-latest.json"
AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_REPORT = REPORTS_DIR / "agent-company-department-schema-plan-latest.md"
AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_JSON = REPORTS_DIR / "agent-company-department-schema-plan-latest.json"
AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON = REPORTS_DIR / "agent-company-department-schema-plan-validation-latest.json"
AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_REPORT = REPORTS_DIR / "agent-company-report-only-migration-draft-latest.md"
AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_JSON = REPORTS_DIR / "agent-company-report-only-migration-draft-latest.json"
AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON = REPORTS_DIR / "agent-company-report-only-migration-draft-validation-latest.json"
AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_REPORT = REPORTS_DIR / "agent-company-migration-apply-preflight-latest.md"
AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_JSON = REPORTS_DIR / "agent-company-migration-apply-preflight-latest.json"
AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-apply-preflight-validation-latest.json"
AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_REPORT = REPORTS_DIR / "agent-company-migration-operator-review-latest.md"
AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_JSON = REPORTS_DIR / "agent-company-migration-operator-review-latest.json"
AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-operator-review-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_REPORT = REPORTS_DIR / "agent-company-migration-decision-intake-contract-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_JSON = REPORTS_DIR / "agent-company-migration-decision-intake-contract-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-intake-contract-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_REPORT = REPORTS_DIR / "agent-company-migration-decision-fixture-suite-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_JSON = REPORTS_DIR / "agent-company-migration-decision-fixture-suite-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-fixture-suite-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_REPORT = REPORTS_DIR / "agent-company-migration-decision-fixture-runner-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_JSON = REPORTS_DIR / "agent-company-migration-decision-fixture-runner-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-fixture-runner-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-scaffold-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-scaffold-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-scaffold-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-module-draft-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-module-draft-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-module-draft-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_REPORT = REPORTS_DIR / "agent-company-migration-decision-module-fixture-checks-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_JSON = REPORTS_DIR / "agent-company-migration-decision-module-fixture-checks-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-module-fixture-checks-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-module-file-draft-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-module-file-draft-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-module-file-draft-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-static-review-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-static-review-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-static-review-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-install-preflight-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-preflight-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-preflight-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-install-review-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-review-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-review-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-intake-contract-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-intake-contract-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-intake-contract-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-fixture-suite-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-fixture-suite-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-fixture-suite-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-runner-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-runner-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-runner-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-runner-review-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-runner-review-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-install-decision-runner-review-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-intake-contract-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-intake-contract-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-intake-contract-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-fixture-suite-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-fixture-suite-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-fixture-suite-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-runner-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-runner-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-runner-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-runner-review-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-runner-review-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-decision-runner-review-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-request-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-request-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-request-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-intake-contract-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-intake-contract-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-intake-contract-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-fixture-suite-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-fixture-suite-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-fixture-suite-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-runner-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-runner-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-runner-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-runner-review-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-runner-review-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-runner-review-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-preflight-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-preflight-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-preflight-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-contract-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-contract-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-contract-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-fixture-suite-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-fixture-suite-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-fixture-suite-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-runner-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-runner-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-runner-validation-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_REPORT = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-runner-review-latest.md"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-runner-review-latest.json"
AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON = REPORTS_DIR / "agent-company-migration-decision-parser-write-approval-response-application-packet-runner-review-validation-latest.json"

__all__ = [
    "AGENT_COMPANY_INFRASTRUCTURE_RADAR_REPORT",
    "AGENT_COMPANY_INFRASTRUCTURE_RADAR_JSON",
    "AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON",
    "AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_REPORT",
    "AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_JSON",
    "AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON",
    "AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_REPORT",
    "AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_JSON",
    "AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON",
    "AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_REPORT",
    "AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_JSON",
    "AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_REPORT",
    "AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_JSON",
    "AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_REPORT",
    "AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_JSON",
    "AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_REPORT",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_JSON",
    "AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON",
]
