"""CEO decision report path constants for Agent Company."""

from __future__ import annotations

from .paths import REPORTS_DIR

CEO_REVIEW_REPORT = REPORTS_DIR / "ceo-review-latest.md"
CEO_GATE_BLOCKER_BOARD_REPORT = REPORTS_DIR / "ceo-gate-blocker-board-latest.md"
CEO_GATE_BLOCKER_BOARD_JSON = REPORTS_DIR / "ceo-gate-blocker-board-latest.json"
CEO_GATE_BLOCKER_BOARD_VALIDATION_JSON = REPORTS_DIR / "ceo-gate-blocker-board-validation-latest.json"
CEO_BLOCKER_TRIAGE_REPORT = REPORTS_DIR / "ceo-blocker-triage-latest.md"
CEO_BLOCKER_TRIAGE_JSON = REPORTS_DIR / "ceo-blocker-triage-latest.json"
CEO_BLOCKER_TRIAGE_VALIDATION_JSON = REPORTS_DIR / "ceo-blocker-triage-validation-latest.json"
CEO_DECISION_PACKET_DRAFTS_REPORT = REPORTS_DIR / "ceo-decision-packet-drafts-latest.md"
CEO_DECISION_PACKET_DRAFTS_JSON = REPORTS_DIR / "ceo-decision-packet-drafts-latest.json"
CEO_DECISION_PACKET_DRAFTS_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-packet-drafts-validation-latest.json"
CEO_DECISION_INTAKE_GUARD_REPORT = REPORTS_DIR / "ceo-decision-intake-guard-latest.md"
CEO_DECISION_INTAKE_GUARD_JSON = REPORTS_DIR / "ceo-decision-intake-guard-latest.json"
CEO_DECISION_INTAKE_GUARD_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-intake-guard-validation-latest.json"
CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_REPORT = REPORTS_DIR / "ceo-decision-intake-negative-fixtures-latest.md"
CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_JSON = REPORTS_DIR / "ceo-decision-intake-negative-fixtures-latest.json"
CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-intake-negative-fixtures-validation-latest.json"
CEO_DECISION_PARSER_PREFLIGHT_REPORT = REPORTS_DIR / "ceo-decision-parser-preflight-latest.md"
CEO_DECISION_PARSER_PREFLIGHT_JSON = REPORTS_DIR / "ceo-decision-parser-preflight-latest.json"
CEO_DECISION_PARSER_PREFLIGHT_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-preflight-validation-latest.json"
CEO_DECISION_PARSER_DRY_RUN_CONTRACT_REPORT = REPORTS_DIR / "ceo-decision-parser-dry-run-contract-latest.md"
CEO_DECISION_PARSER_DRY_RUN_CONTRACT_JSON = REPORTS_DIR / "ceo-decision-parser-dry-run-contract-latest.json"
CEO_DECISION_PARSER_DRY_RUN_CONTRACT_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-dry-run-contract-validation-latest.json"
CEO_DECISION_PARSER_POSITIVE_FIXTURE_REPORT = REPORTS_DIR / "ceo-decision-parser-positive-fixture-latest.md"
CEO_DECISION_PARSER_POSITIVE_FIXTURE_JSON = REPORTS_DIR / "ceo-decision-parser-positive-fixture-latest.json"
CEO_DECISION_PARSER_POSITIVE_FIXTURE_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-positive-fixture-validation-latest.json"
CEO_DECISION_PARSER_FIXTURE_SUITE_REPORT = REPORTS_DIR / "ceo-decision-parser-fixture-suite-latest.md"
CEO_DECISION_PARSER_FIXTURE_SUITE_JSON = REPORTS_DIR / "ceo-decision-parser-fixture-suite-latest.json"
CEO_DECISION_PARSER_FIXTURE_SUITE_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-fixture-suite-validation-latest.json"
CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_REPORT = REPORTS_DIR / "ceo-decision-parser-report-only-harness-latest.md"
CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_JSON = REPORTS_DIR / "ceo-decision-parser-report-only-harness-latest.json"
CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-report-only-harness-validation-latest.json"
CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-report-only-runner-latest.md"
CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-report-only-runner-latest.json"
CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-report-only-runner-validation-latest.json"
CEO_DECISION_PARSER_MUTATION_PREFLIGHT_REPORT = REPORTS_DIR / "ceo-decision-parser-mutation-preflight-latest.md"
CEO_DECISION_PARSER_MUTATION_PREFLIGHT_JSON = REPORTS_DIR / "ceo-decision-parser-mutation-preflight-latest.json"
CEO_DECISION_PARSER_MUTATION_PREFLIGHT_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-mutation-preflight-validation-latest.json"
CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-negative-fixtures-latest.md"
CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_JSON = REPORTS_DIR / "ceo-decision-parser-apply-negative-fixtures-latest.json"
CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-negative-fixtures-validation-latest.json"
CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-guard-runner-latest.md"
CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-guard-runner-latest.json"
CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-guard-runner-validation-latest.json"
CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-positive-fixture-latest.md"
CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_JSON = REPORTS_DIR / "ceo-decision-parser-apply-positive-fixture-latest.json"
CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-positive-fixture-validation-latest.json"
CEO_DECISION_PARSER_APPLY_DRY_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-dry-runner-latest.md"
CEO_DECISION_PARSER_APPLY_DRY_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-dry-runner-latest.json"
CEO_DECISION_PARSER_APPLY_DRY_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-dry-runner-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-negative-fixtures-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-negative-fixtures-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-negative-fixtures-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-guard-runner-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-guard-runner-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-guard-runner-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-positive-fixture-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-positive-fixture-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-positive-fixture-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-positive-runner-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-positive-runner-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-positive-runner-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-operator-approval-packet-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-operator-approval-packet-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-operator-approval-packet-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-no-approval-blocker-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-no-approval-blocker-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-no-approval-blocker-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-decision-intake-packet-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-decision-intake-packet-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-decision-intake-packet-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-negative-fixtures-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-negative-fixtures-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-negative-fixtures-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-guard-runner-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-guard-runner-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-guard-runner-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-positive-fixture-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-positive-fixture-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-positive-fixture-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-positive-runner-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-positive-runner-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-positive-runner-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-preflight-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-preflight-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-preflight-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-operator-apply-approval-packet-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-operator-apply-approval-packet-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-operator-apply-approval-packet-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-contract-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-contract-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-contract-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-negative-fixtures-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-negative-fixtures-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-negative-fixtures-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-guard-runner-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-guard-runner-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-guard-runner-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-fixture-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-fixture-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-fixture-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-runner-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-runner-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-runner-validation-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_REPORT = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-closeout-latest.md"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-closeout-latest.json"
CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_VALIDATION_JSON = REPORTS_DIR / "ceo-decision-parser-apply-readiness-signed-decision-apply-command-closeout-validation-latest.json"

__all__ = [
    "CEO_REVIEW_REPORT",
    "CEO_GATE_BLOCKER_BOARD_REPORT",
    "CEO_GATE_BLOCKER_BOARD_JSON",
    "CEO_GATE_BLOCKER_BOARD_VALIDATION_JSON",
    "CEO_BLOCKER_TRIAGE_REPORT",
    "CEO_BLOCKER_TRIAGE_JSON",
    "CEO_BLOCKER_TRIAGE_VALIDATION_JSON",
    "CEO_DECISION_PACKET_DRAFTS_REPORT",
    "CEO_DECISION_PACKET_DRAFTS_JSON",
    "CEO_DECISION_PACKET_DRAFTS_VALIDATION_JSON",
    "CEO_DECISION_INTAKE_GUARD_REPORT",
    "CEO_DECISION_INTAKE_GUARD_JSON",
    "CEO_DECISION_INTAKE_GUARD_VALIDATION_JSON",
    "CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_REPORT",
    "CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_JSON",
    "CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_VALIDATION_JSON",
    "CEO_DECISION_PARSER_PREFLIGHT_REPORT",
    "CEO_DECISION_PARSER_PREFLIGHT_JSON",
    "CEO_DECISION_PARSER_PREFLIGHT_VALIDATION_JSON",
    "CEO_DECISION_PARSER_DRY_RUN_CONTRACT_REPORT",
    "CEO_DECISION_PARSER_DRY_RUN_CONTRACT_JSON",
    "CEO_DECISION_PARSER_DRY_RUN_CONTRACT_VALIDATION_JSON",
    "CEO_DECISION_PARSER_POSITIVE_FIXTURE_REPORT",
    "CEO_DECISION_PARSER_POSITIVE_FIXTURE_JSON",
    "CEO_DECISION_PARSER_POSITIVE_FIXTURE_VALIDATION_JSON",
    "CEO_DECISION_PARSER_FIXTURE_SUITE_REPORT",
    "CEO_DECISION_PARSER_FIXTURE_SUITE_JSON",
    "CEO_DECISION_PARSER_FIXTURE_SUITE_VALIDATION_JSON",
    "CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_REPORT",
    "CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_JSON",
    "CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_VALIDATION_JSON",
    "CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_REPORT",
    "CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_JSON",
    "CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_MUTATION_PREFLIGHT_REPORT",
    "CEO_DECISION_PARSER_MUTATION_PREFLIGHT_JSON",
    "CEO_DECISION_PARSER_MUTATION_PREFLIGHT_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_REPORT",
    "CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_JSON",
    "CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_REPORT",
    "CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_JSON",
    "CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_REPORT",
    "CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_JSON",
    "CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_DRY_RUNNER_REPORT",
    "CEO_DECISION_PARSER_APPLY_DRY_RUNNER_JSON",
    "CEO_DECISION_PARSER_APPLY_DRY_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_VALIDATION_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_REPORT",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_JSON",
    "CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_VALIDATION_JSON",
]
