from __future__ import annotations

"""Compatibility facade for the local digital-products workflow."""

from .digital_products_discovery import (
    digital_products_demand_questions,
    write_digital_products_local_demand_proof,
    digital_products_memo_candidates,
    write_digital_products_local_demand_memo,
    digital_products_build_brief_sections,
    digital_products_build_brief_deliverables,
    digital_products_build_brief_acceptance_criteria,
    write_digital_products_local_build_brief,
)

from .digital_products_assets import (
    digital_products_asset_outline_components,
    digital_products_positioning_template_fields,
    digital_products_sample_positioning_sections,
    write_digital_products_local_asset_outline,
    digital_products_positioning_answers,
    digital_products_launch_checklist_rows,
    digital_products_asset_boundary_notes,
    write_digital_products_local_asset_draft,
    digital_products_quality_checks,
    digital_products_quality_revision_items,
    write_digital_products_local_quality_pass,
    digital_products_package_files,
    digital_products_readme_sections,
    write_digital_products_local_packaging_manifest,
    digital_products_screenshot_rows,
    digital_products_qa_rows,
    digital_products_post_launch_prompts,
    write_digital_products_local_package_files,
    digital_products_completeness_checks,
    digital_products_missing_file_stubs,
    write_digital_products_local_completeness_check,
)

from .digital_products_review import (
    digital_products_private_review_artifacts,
    digital_products_private_review_questions,
    digital_products_private_review_decision_options,
    write_digital_products_local_private_review_packet,
    digital_products_private_review_answers,
    digital_products_private_review_revision_items,
    write_digital_products_local_private_review_decision,
    digital_products_revision_pass_files,
    write_digital_products_local_revision_pass,
    digital_products_revised_completeness_checks,
    write_digital_products_local_revised_completeness,
    digital_products_gate_decision_options,
    write_digital_products_local_gate_decision_packet,
    digital_products_gate_choice_followup_items,
    write_digital_products_local_gate_choice,
)

from .digital_products_approval import (
    digital_products_copy_polish_files,
    write_digital_products_local_copy_polish,
    digital_products_post_polish_readiness_checks,
    write_digital_products_local_post_polish_readiness,
    digital_products_approval_request_draft_packets,
    write_digital_products_local_approval_request_drafts,
    write_digital_products_local_operator_approval_brief,
    write_digital_products_local_post_approval_simulation_plan,
    write_digital_products_local_gated_hold_register,
)

__all__ = [
    "digital_products_demand_questions",
    "write_digital_products_local_demand_proof",
    "digital_products_memo_candidates",
    "write_digital_products_local_demand_memo",
    "digital_products_build_brief_sections",
    "digital_products_build_brief_deliverables",
    "digital_products_build_brief_acceptance_criteria",
    "write_digital_products_local_build_brief",
    "digital_products_asset_outline_components",
    "digital_products_positioning_template_fields",
    "digital_products_sample_positioning_sections",
    "write_digital_products_local_asset_outline",
    "digital_products_positioning_answers",
    "digital_products_launch_checklist_rows",
    "digital_products_asset_boundary_notes",
    "write_digital_products_local_asset_draft",
    "digital_products_quality_checks",
    "digital_products_quality_revision_items",
    "write_digital_products_local_quality_pass",
    "digital_products_package_files",
    "digital_products_readme_sections",
    "write_digital_products_local_packaging_manifest",
    "digital_products_screenshot_rows",
    "digital_products_qa_rows",
    "digital_products_post_launch_prompts",
    "write_digital_products_local_package_files",
    "digital_products_completeness_checks",
    "digital_products_missing_file_stubs",
    "write_digital_products_local_completeness_check",
    "digital_products_private_review_artifacts",
    "digital_products_private_review_questions",
    "digital_products_private_review_decision_options",
    "write_digital_products_local_private_review_packet",
    "digital_products_private_review_answers",
    "digital_products_private_review_revision_items",
    "write_digital_products_local_private_review_decision",
    "digital_products_revision_pass_files",
    "write_digital_products_local_revision_pass",
    "digital_products_revised_completeness_checks",
    "write_digital_products_local_revised_completeness",
    "digital_products_gate_decision_options",
    "write_digital_products_local_gate_decision_packet",
    "digital_products_gate_choice_followup_items",
    "write_digital_products_local_gate_choice",
    "digital_products_copy_polish_files",
    "write_digital_products_local_copy_polish",
    "digital_products_post_polish_readiness_checks",
    "write_digital_products_local_post_polish_readiness",
    "digital_products_approval_request_draft_packets",
    "write_digital_products_local_approval_request_drafts",
    "write_digital_products_local_operator_approval_brief",
    "write_digital_products_local_post_approval_simulation_plan",
    "write_digital_products_local_gated_hold_register",
]
