from __future__ import annotations

from typing import Any

"""CEO apply-readiness approval and intake integrity specs."""

from .constants import (
    CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON,
)


def ceo_readiness_approval_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            'id': 'ceo_decision_parser_apply_readiness_operator_approval_packet',
            'label': 'CEO Decision Parser Apply Readiness Operator Approval Packet',
            'path': CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON,
            'count_key': 'operator_approval_packet_count',
            'expected': {
                'schema_version': 'agent_company.ceo_decision_parser_apply_readiness_operator_approval_packet_validation.v1',
                'packet_lane_id': 'platform_engineering',
                'packet_task_id': 'task-ceo-decision-parser-apply-readiness-operator-approval-packet-20260616',
                'source_runner_task_id': 'task-ceo-decision-parser-apply-readiness-positive-runner-20260616',
                'operator_approval_packet_count': 1,
                'target_service_request_count': 1,
                'planned_field_update_count': 2,
                'rollback_check_count': 4,
                'required_operator_approval_count': 5,
                'approval_statement_count': 5,
                'mutation_applied_count': 0,
                'queue_mutation_count': 0,
                'approval_request_count': 0,
                'target_status_before': 'needs_review',
                'target_status_after': 'needs_review',
                'local_decision': 'ceo_decision_parser_apply_readiness_operator_approval_packet_ready_no_request',
                'recommended_default': 'wait_for_explicit_operator_apply_approval',
                'live_tasks_created': 1,
                'live_tasks_completed': 1,
                'tasks_table_rows_before': 210,
                'tasks_table_rows_after': 211,
                'task_rows_inserted_by_packet': 1,
                'lane_evidence_rows_before': 118,
                'lane_evidence_rows_after': 119,
                'evidence_rows_inserted_or_updated': 1,
                'all_checks_passed': True,
                'failure_count': 0,
                'browser_sessions_started': 0,
                'account_actions': False,
                'wallet_actions': False,
                'payment_actions': False,
                'public_actions': False,
                'security_testing_actions': False,
                'real_money_actions': False,
                'service_requests_updated': 0,
                'service_requests_assigned': 0,
                'worker_starts': 0,
                'api_calls': False,
                'external_side_effects': False,
            },
        },
        {
            'id': 'ceo_decision_parser_apply_readiness_no_approval_blocker',
            'label': 'CEO Decision Parser Apply Readiness No Approval Blocker',
            'path': CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON,
            'count_key': 'blocked_apply_attempt_count',
            'expected': {
                'schema_version': 'agent_company.ceo_decision_parser_apply_readiness_no_approval_blocker_validation.v1',
                'blocker_lane_id': 'platform_engineering',
                'blocker_task_id': 'task-ceo-decision-parser-apply-readiness-no-approval-blocker-20260616',
                'source_packet_task_id': 'task-ceo-decision-parser-apply-readiness-operator-approval-packet-20260616',
                'blocked_apply_attempt_count': 1,
                'blocked_reason_count': 4,
                'operator_approval_packet_count': 1,
                'target_service_request_count': 1,
                'planned_field_update_count': 2,
                'approval_statement_count': 5,
                'apply_command_enabled': False,
                'approval_request_emitted': False,
                'explicit_operator_approval_present': False,
                'mutation_applied_count': 0,
                'queue_mutation_count': 0,
                'approval_request_count': 0,
                'target_status_before': 'needs_review',
                'target_status_after': 'needs_review',
                'local_decision': 'ceo_decision_parser_apply_readiness_no_approval_blocked_no_mutation',
                'recommended_default': 'do_not_add_apply_command_until_explicit_operator_approval_exists',
                'live_tasks_created': 1,
                'live_tasks_completed': 1,
                'tasks_table_rows_before': 211,
                'tasks_table_rows_after': 212,
                'task_rows_inserted_by_blocker': 1,
                'lane_evidence_rows_before': 119,
                'lane_evidence_rows_after': 120,
                'evidence_rows_inserted_or_updated': 1,
                'all_checks_passed': True,
                'failure_count': 0,
                'browser_sessions_started': 0,
                'account_actions': False,
                'wallet_actions': False,
                'payment_actions': False,
                'public_actions': False,
                'security_testing_actions': False,
                'real_money_actions': False,
                'service_requests_updated': 0,
                'service_requests_assigned': 0,
                'worker_starts': 0,
                'api_calls': False,
                'external_side_effects': False,
            },
        },
        {
            'id': 'ceo_decision_parser_apply_readiness_decision_intake_packet',
            'label': 'CEO Decision Parser Apply Readiness Decision Intake Packet',
            'path': CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON,
            'count_key': 'decision_intake_packet_count',
            'expected': {
                'schema_version': 'agent_company.ceo_decision_parser_apply_readiness_decision_intake_packet_validation.v1',
                'intake_lane_id': 'platform_engineering',
                'intake_task_id': 'task-ceo-decision-parser-apply-readiness-decision-intake-packet-20260616',
                'source_blocker_task_id': 'task-ceo-decision-parser-apply-readiness-no-approval-blocker-20260616',
                'source_packet_task_id': 'task-ceo-decision-parser-apply-readiness-operator-approval-packet-20260616',
                'decision_intake_packet_count': 1,
                'decision_field_count': 12,
                'approval_statement_count': 5,
                'blocked_apply_attempt_count': 1,
                'target_service_request_count': 1,
                'requires_explicit_signed_decision': True,
                'requires_exact_target_request_id': True,
                'requires_approval_scope_text': True,
                'requires_decision_note_text': True,
                'requires_rollback_snapshot_match': True,
                'requires_scope_expiration': True,
                'requires_no_external_side_effects_default': True,
                'approval_granted_by_intake_packet': False,
                'apply_command_enabled': False,
                'mutation_applied_count': 0,
                'queue_mutation_count': 0,
                'approval_request_count': 0,
                'target_status_before': 'needs_review',
                'target_status_after': 'needs_review',
                'local_decision': 'ceo_decision_parser_apply_readiness_decision_intake_packet_ready_no_approval',
                'recommended_default': 'collect_signed_operator_decision_before_apply_command',
                'live_tasks_created': 1,
                'live_tasks_completed': 1,
                'tasks_table_rows_before': 212,
                'tasks_table_rows_after': 213,
                'task_rows_inserted_by_intake': 1,
                'lane_evidence_rows_before': 120,
                'lane_evidence_rows_after': 121,
                'evidence_rows_inserted_or_updated': 1,
                'all_checks_passed': True,
                'failure_count': 0,
                'browser_sessions_started': 0,
                'account_actions': False,
                'wallet_actions': False,
                'payment_actions': False,
                'public_actions': False,
                'security_testing_actions': False,
                'real_money_actions': False,
                'service_requests_updated': 0,
                'service_requests_assigned': 0,
                'worker_starts': 0,
                'api_calls': False,
                'external_side_effects': False,
            },
        }
    ]


__all__ = ["ceo_readiness_approval_integrity_specs"]
