from __future__ import annotations

from typing import Any

"""CEO signed-decision readiness integrity specs."""

from .constants import (
    CEO_BLOCKER_TRIAGE_VALIDATION_JSON,
    CEO_DECISION_INTAKE_GUARD_VALIDATION_JSON,
    CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PACKET_DRAFTS_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_DRY_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_DRY_RUN_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_FIXTURE_SUITE_VALIDATION_JSON,
    CEO_DECISION_PARSER_MUTATION_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_VALIDATION_JSON,
    CEO_GATE_BLOCKER_BOARD_VALIDATION_JSON,
)


def ceo_signed_decision_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_negative_fixtures",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Negative Fixtures",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_VALIDATION_JSON,
            "count_key": "negative_signed_decision_fixture_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_negative_fixtures_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-negative-fixtures-20260616",
                "source_intake_task_id": "task-ceo-decision-parser-apply-readiness-decision-intake-packet-20260616",
                "negative_signed_decision_fixture_count": 6,
                "expected_rejection_count": 6,
                "decision_field_count": 12,
                "approval_statement_count": 5,
                "target_service_request_count": 1,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_negative_fixtures_ready",
                "recommended_default": "run_signed_decision_guard_before_any_apply_command",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 213,
                "tasks_table_rows_after": 214,
                "task_rows_inserted_by_fixtures": 1,
                "lane_evidence_rows_before": 121,
                "lane_evidence_rows_after": 122,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_guard_runner",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Guard Runner",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_VALIDATION_JSON,
            "count_key": "signed_decision_guard_execution_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_guard_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-guard-runner-20260616",
                "source_fixtures_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-negative-fixtures-20260616",
                "negative_signed_decision_fixture_count": 6,
                "signed_decision_guard_execution_count": 6,
                "rejected_signed_decision_count": 6,
                "accepted_signed_decision_count": 0,
                "expected_rejection_match_count": 6,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_guard_runner_passed_no_mutations",
                "recommended_default": "keep_apply_disabled_until_signed_decision_guard_passes_positive_fixture",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 214,
                "tasks_table_rows_after": 215,
                "task_rows_inserted_by_runner": 1,
                "lane_evidence_rows_before": 122,
                "lane_evidence_rows_after": 123,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_positive_fixture",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Positive Fixture",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_VALIDATION_JSON,
            "count_key": "positive_signed_decision_fixture_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_positive_fixture_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-positive-fixture-20260616",
                "source_guard_runner_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-guard-runner-20260616",
                "positive_signed_decision_fixture_count": 1,
                "expected_acceptance_count": 1,
                "decision_field_count": 12,
                "approval_statement_count": 5,
                "target_service_request_count": 1,
                "signed_decision_preview_only": True,
                "apply_command_enabled": False,
                "approval_granted_by_fixture": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_positive_fixture_ready_preview_only",
                "recommended_default": "positive_signed_decision_fixture_requires_separate_positive_runner",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 215,
                "tasks_table_rows_after": 216,
                "task_rows_inserted_by_fixture": 1,
                "lane_evidence_rows_before": 123,
                "lane_evidence_rows_after": 124,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_positive_runner",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Positive Runner",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_VALIDATION_JSON,
            "count_key": "signed_decision_positive_execution_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_positive_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-positive-runner-20260616",
                "source_fixture_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-positive-fixture-20260616",
                "positive_signed_decision_fixture_count": 1,
                "signed_decision_positive_execution_count": 1,
                "accepted_signed_decision_count": 1,
                "rejected_signed_decision_count": 0,
                "expected_acceptance_match_count": 1,
                "preview_state_match_count": 1,
                "real_mutation_allowed_count": 0,
                "apply_command_enabled": False,
                "approval_granted_by_runner": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_positive_runner_passed_preview_only",
                "recommended_default": "positive_signed_decision_runner_still_requires_separate_operator_apply_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 216,
                "tasks_table_rows_after": 217,
                "task_rows_inserted_by_runner": 1,
                "lane_evidence_rows_before": 124,
                "lane_evidence_rows_after": 125,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_apply_preflight",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Apply Preflight",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_VALIDATION_JSON,
            "count_key": "apply_preflight_check_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_apply_preflight_validation.v1",
                "preflight_lane_id": "platform_engineering",
                "preflight_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-preflight-20260616",
                "source_runner_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-positive-runner-20260616",
                "apply_preflight_check_count": 1,
                "accepted_signed_decision_count": 1,
                "apply_blocked_count": 1,
                "blocked_reason_count": 5,
                "apply_command_enabled": False,
                "approval_granted_by_runner": False,
                "explicit_operator_apply_approval_present": False,
                "real_mutation_allowed_count": 0,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_apply_preflight_blocked_no_mutation",
                "recommended_default": "wait_for_explicit_operator_apply_approval_before_mutating_service_request",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 217,
                "tasks_table_rows_after": 218,
                "task_rows_inserted_by_preflight": 1,
                "lane_evidence_rows_before": 125,
                "lane_evidence_rows_after": 126,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_operator_apply_approval_packet",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Operator Apply Approval Packet",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_VALIDATION_JSON,
            "count_key": "operator_apply_approval_packet_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_operator_apply_approval_packet_validation.v1",
                "packet_lane_id": "platform_engineering",
                "packet_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-operator-apply-approval-packet-20260616",
                "source_preflight_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-preflight-20260616",
                "operator_apply_approval_packet_count": 1,
                "required_approval_field_count": 8,
                "required_confirmation_count": 6,
                "approval_granted_by_packet": False,
                "explicit_operator_apply_approval_present": False,
                "apply_command_enabled": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_operator_apply_approval_packet_ready_no_mutation",
                "recommended_default": "operator_must_explicitly_approve_before_apply_command_is_enabled",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 218,
                "tasks_table_rows_after": 219,
                "task_rows_inserted_by_packet": 1,
                "lane_evidence_rows_before": 126,
                "lane_evidence_rows_after": 127,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["ceo_signed_decision_integrity_specs"]
