from __future__ import annotations

from typing import Any

"""Money-path, paid-code, and digital-product lane integrity specs."""

from .constants import (
    COMPANY_EXPANSION_GAP_MAP_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_VALIDATION_JSON,
    FIRST_LOCAL_EVIDENCE_PACKETS_VALIDATION_JSON,
    FIRST_RANKED_MANAGER_PROOF_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PACKETS_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_PREFLIGHT_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_QUEUE_VALIDATION_JSON,
    MONEY_PATH_COVERAGE_AUDIT_VALIDATION_JSON,
    PAID_CODE_BROWSER_REFRESH_DECISION_PACKET_VALIDATION_JSON,
    PAID_CODE_DUPLICATE_CHECK_WORKSHEET_VALIDATION_JSON,
    PAID_CODE_LOCAL_WORKSHEET_ANSWERS_VALIDATION_JSON,
)


def paid_code_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "paid_code_duplicate_check_worksheet",
            "label": "Paid-Code Duplicate-Check Worksheet",
            "path": PAID_CODE_DUPLICATE_CHECK_WORKSHEET_VALIDATION_JSON,
            "count_key": "worksheet_item_count",
            "expected": {
                "schema_version": "agent_company.paid_code_duplicate_check_worksheet_validation.v1",
                "worksheet_lane_id": "paid_code_bounties",
                "worksheet_task_id": "task-paid-code-duplicate-check-worksheet-20260615",
                "source_proof_task_id": "task-paid_code_bounties-first-local-proof-20260615",
                "worksheet_item_count": 12,
                "blocked_by_gate_count": 6,
                "local_only_item_count": 6,
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 145,
                "tasks_table_rows_after": 146,
                "task_rows_inserted_by_worksheet": 1,
                "lane_evidence_rows_before": 74,
                "lane_evidence_rows_after": 75,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "paid_code_local_worksheet_answers",
            "label": "Paid-Code Local Worksheet Answers",
            "path": PAID_CODE_LOCAL_WORKSHEET_ANSWERS_VALIDATION_JSON,
            "count_key": "local_answer_count",
            "expected": {
                "schema_version": "agent_company.paid_code_local_worksheet_answers_validation.v1",
                "answer_lane_id": "paid_code_bounties",
                "answer_task_id": "task-paid-code-local-worksheet-answers-20260615",
                "source_worksheet_task_id": "task-paid-code-duplicate-check-worksheet-20260615",
                "worksheet_item_count": 12,
                "local_answer_count": 6,
                "gated_item_count": 6,
                "local_items_answered": True,
                "gated_items_preserved": True,
                "recommended_local_decision": "no_live_claim_without_refresh_gate",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 147,
                "tasks_table_rows_after": 148,
                "task_rows_inserted_by_answers": 1,
                "lane_evidence_rows_before": 75,
                "lane_evidence_rows_after": 76,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "paid_code_browser_refresh_decision_packet",
            "label": "Paid-Code Browser Refresh Decision Packet",
            "path": PAID_CODE_BROWSER_REFRESH_DECISION_PACKET_VALIDATION_JSON,
            "count_key": "scope_item_count",
            "expected": {
                "schema_version": "agent_company.paid_code_browser_refresh_decision_packet_validation.v1",
                "request_id": "req-next-wave-paid-code-algora-archestra-browser-readonly-20260614",
                "request_status": "needs_review",
                "request_lane_id": "paid_code_bounties",
                "source_answers_task_id": "task-paid-code-local-worksheet-answers-20260615",
                "scope_item_count": 5,
                "forbidden_action_count": 6,
                "approval_required": True,
                "decision_granted": False,
                "decision_rejected": False,
                "tasks_table_rows_before": 149,
                "tasks_table_rows_after": 149,
                "task_rows_inserted_by_packet": 0,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]

