from __future__ import annotations

from typing import Any

"""CEO parser apply-runner integrity specs."""

from .constants import (
    CEO_BLOCKER_TRIAGE_VALIDATION_JSON,
    CEO_DECISION_INTAKE_GUARD_VALIDATION_JSON,
    CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PACKET_DRAFTS_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_DRY_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_DRY_RUN_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_FIXTURE_SUITE_VALIDATION_JSON,
    CEO_DECISION_PARSER_MUTATION_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_VALIDATION_JSON,
    CEO_GATE_BLOCKER_BOARD_VALIDATION_JSON,
)


def ceo_apply_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "ceo_decision_parser_apply_negative_fixtures",
            "label": "CEO Decision Parser Apply Negative Fixtures",
            "path": CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_VALIDATION_JSON,
            "count_key": "negative_apply_fixture_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_negative_fixtures_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-ceo-decision-parser-apply-negative-fixtures-20260616",
                "source_preflight_task_id": "task-ceo-decision-parser-mutation-preflight-20260616",
                "negative_apply_fixture_count": 6,
                "expected_rejection_count": 6,
                "accepted_apply_count": 0,
                "required_apply_field_count": 7,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "local_decision": "ceo_decision_parser_apply_negative_fixtures_ready",
                "recommended_default": "reject_apply_without_explicit_mutation_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 201,
                "tasks_table_rows_after": 202,
                "task_rows_inserted_by_fixtures": 1,
                "lane_evidence_rows_before": 109,
                "lane_evidence_rows_after": 110,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_guard_runner",
            "label": "CEO Decision Parser Apply Guard Runner",
            "path": CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_VALIDATION_JSON,
            "count_key": "apply_guard_execution_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_guard_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-ceo-decision-parser-apply-guard-runner-20260616",
                "source_fixtures_task_id": "task-ceo-decision-parser-apply-negative-fixtures-20260616",
                "negative_apply_fixture_count": 6,
                "apply_guard_execution_count": 6,
                "rejected_apply_count": 6,
                "accepted_apply_count": 0,
                "expected_rejection_match_count": 6,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "local_decision": "ceo_decision_parser_apply_guard_runner_passed_no_mutations",
                "recommended_default": "keep_apply_path_disabled_until_explicit_mutation_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 202,
                "tasks_table_rows_after": 203,
                "task_rows_inserted_by_runner": 1,
                "lane_evidence_rows_before": 110,
                "lane_evidence_rows_after": 111,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_positive_fixture",
            "label": "CEO Decision Parser Apply Positive Fixture",
            "path": CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_VALIDATION_JSON,
            "count_key": "positive_apply_fixture_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_positive_fixture_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-ceo-decision-parser-apply-positive-fixture-20260616",
                "source_guard_runner_task_id": "task-ceo-decision-parser-apply-guard-runner-20260616",
                "positive_apply_fixture_count": 1,
                "target_service_request_count": 1,
                "expected_preview_update_count": 1,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_positive_fixture_ready_preview_only",
                "recommended_default": "preview_single_service_request_update_before_apply",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 203,
                "tasks_table_rows_after": 204,
                "task_rows_inserted_by_fixture": 1,
                "lane_evidence_rows_before": 111,
                "lane_evidence_rows_after": 112,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_dry_runner",
            "label": "CEO Decision Parser Apply Dry Runner",
            "path": CEO_DECISION_PARSER_APPLY_DRY_RUNNER_VALIDATION_JSON,
            "count_key": "apply_dry_run_execution_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_dry_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-ceo-decision-parser-apply-dry-runner-20260616",
                "source_positive_fixture_task_id": "task-ceo-decision-parser-apply-positive-fixture-20260616",
                "positive_apply_fixture_count": 1,
                "apply_dry_run_execution_count": 1,
                "accepted_apply_preview_count": 1,
                "expected_preview_match_count": 1,
                "preview_update_count": 1,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_dry_runner_passed_preview_only",
                "recommended_default": "require_operator_apply_approval_before_real_update",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 204,
                "tasks_table_rows_after": 205,
                "task_rows_inserted_by_runner": 1,
                "lane_evidence_rows_before": 112,
                "lane_evidence_rows_after": 113,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["ceo_apply_integrity_specs"]
