from __future__ import annotations

from typing import Any

"""
Durable runtime contract and scaffolding integrity specs.
"""

from .constants import (
    DURABLE_RUNTIME_IMPLEMENTATION_PREFLIGHT_VALIDATION_JSON,
    DURABLE_RUNTIME_INTERFACE_CONTRACT_VALIDATION_JSON,
    DURABLE_RUNTIME_INTERFACE_NEGATIVE_FIXTURES_VALIDATION_JSON,
    DURABLE_RUNTIME_REPORT_ONLY_FIXTURES_VALIDATION_JSON,
    DURABLE_RUNTIME_REPORT_ONLY_SCAFFOLDING_ARTIFACTS_VALIDATION_JSON,
    DURABLE_RUNTIME_REPORT_ONLY_SCAFFOLDING_PACKET_VALIDATION_JSON,
    DURABLE_SERVICE_WORKER_INTEGRATION_VALIDATION_JSON,
)


def durable_runtime_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "durable_service_worker_integration",
            "label": "Durable Adapter Service-Worker Integration",
            "path": DURABLE_SERVICE_WORKER_INTEGRATION_VALIDATION_JSON,
            "count_key": "reducer_result_count",
            "expected": {
                "schema_version": "temporal_inngest_adapter_service_worker_refresh_integration_validation.v1",
                "reducer_result_count": 14,
                "parked_rows_mapped_to_review_refresh": 11,
                "terminal_completed_rows_mapped_to_no_replay": 1,
                "terminal_rejected_rows_mapped_to_no_revive": 2,
                "human_decision_packet_count_matches_parked_rows": True,
                "post_decision_refresh_plan_count_matches_parked_rows": True,
                "decision_preflight_count_matches_parked_rows": True,
                "model_api_gate_remains_parked": True,
                "model_api_pool_registered": False,
                "no_external_runtime_started": True,
                "no_actions_granted": True,
                "all_checks_passed": True,
                "failure_count": 0,
                "approval_granted": False,
                "rejection_granted": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "durable_runtime_interface_contract",
            "label": "Durable Runtime Interface Contract",
            "path": DURABLE_RUNTIME_INTERFACE_CONTRACT_VALIDATION_JSON,
            "count_key": "interface_contract_count",
            "expected": {
                "schema_version": "temporal_inngest_adapter_runtime_interface_contract_validation.v1",
                "interface_contract_count": 4,
                "reducer_result_count": 14,
                "parked_rows": 11,
                "terminal_rows": 3,
                "workflow_start_allowed": False,
                "activity_schedule_allowed": False,
                "event_emit_allowed": False,
                "runtime_import_allowed": False,
                "forbidden_runtime_import_count": 0,
                "no_forbidden_runtime_imports_detected": True,
                "service_request_mutation_count": 0,
                "model_api_gate_remains_parked": True,
                "model_api_pool_registered": False,
                "all_checks_passed": True,
                "failure_count": 0,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "temporal_server_started": False,
                "temporal_workflows_started": 0,
                "temporal_activities_scheduled": 0,
                "inngest_service_started": False,
                "inngest_events_emitted": 0,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "durable_runtime_interface_negative_fixtures",
            "label": "Durable Runtime Interface Negative Fixtures",
            "path": DURABLE_RUNTIME_INTERFACE_NEGATIVE_FIXTURES_VALIDATION_JSON,
            "count_key": "negative_fixture_count",
            "expected": {
                "schema_version": "temporal_inngest_adapter_runtime_interface_negative_fixtures_validation.v1",
                "negative_fixture_count": 8,
                "rejected_fixture_count": 8,
                "accepted_fixture_count": 0,
                "contract_validation_loaded": True,
                "contract_validation_passed": True,
                "all_negative_fixtures_rejected": True,
                "runtime_import_allowed": False,
                "dependency_install_allowed": False,
                "workflow_start_allowed": False,
                "activity_schedule_allowed": False,
                "event_emit_allowed": False,
                "service_request_mutation_allowed": False,
                "worker_start_allowed": False,
                "api_call_allowed": False,
                "forbidden_runtime_import_count": 0,
                "model_api_gate_remains_parked": True,
                "model_api_pool_registered": False,
                "all_checks_passed": True,
                "failure_count": 0,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "temporal_server_started": False,
                "temporal_workflows_started": 0,
                "temporal_activities_scheduled": 0,
                "inngest_service_started": False,
                "inngest_events_emitted": 0,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "durable_runtime_implementation_preflight",
            "label": "Durable Runtime Implementation Preflight",
            "path": DURABLE_RUNTIME_IMPLEMENTATION_PREFLIGHT_VALIDATION_JSON,
            "count_key": "preflight_check_count",
            "expected": {
                "schema_version": "temporal_inngest_adapter_runtime_implementation_preflight_validation.v1",
                "preflight_check_count": 9,
                "passed_preflight_check_count": 9,
                "upstream_validation_count": 4,
                "upstream_validation_passed_count": 4,
                "runtime_implementation_allowed": False,
                "runtime_code_write_allowed": False,
                "report_only_scaffolding_allowed": True,
                "explicit_runtime_approval_present": False,
                "external_runtime_implementation_allowed_now": False,
                "local_report_only_implementation_allowed_now": True,
                "negative_fixture_count": 8,
                "rejected_fixture_count": 8,
                "accepted_fixture_count": 0,
                "all_negative_fixtures_rejected": True,
                "forbidden_runtime_import_count": 0,
                "no_forbidden_runtime_imports_detected": True,
                "model_api_gate_remains_parked": True,
                "model_api_pool_registered": False,
                "all_checks_passed": True,
                "failure_count": 0,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "temporal_server_started": False,
                "temporal_workflows_started": 0,
                "temporal_activities_scheduled": 0,
                "inngest_service_started": False,
                "inngest_events_emitted": 0,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "durable_runtime_report_only_fixtures",
            "label": "Durable Runtime Report-Only Fixtures",
            "path": DURABLE_RUNTIME_REPORT_ONLY_FIXTURES_VALIDATION_JSON,
            "count_key": "report_only_fixture_count",
            "expected": {
                "schema_version": "temporal_inngest_adapter_runtime_report_only_fixtures_validation.v1",
                "report_only_fixture_count": 5,
                "accepted_report_only_fixture_count": 5,
                "rejected_report_only_fixture_count": 0,
                "runtime_fixture_count": 0,
                "runtime_side_effect_fixture_count": 0,
                "preflight_validation_loaded": True,
                "preflight_validation_passed": True,
                "runtime_implementation_allowed": False,
                "runtime_code_write_allowed": False,
                "report_only_scaffolding_allowed": True,
                "all_report_only_fixtures_allowed": True,
                "forbidden_runtime_import_count": 0,
                "no_forbidden_runtime_imports_detected": True,
                "model_api_gate_remains_parked": True,
                "model_api_pool_registered": False,
                "all_checks_passed": True,
                "failure_count": 0,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "temporal_server_started": False,
                "temporal_workflows_started": 0,
                "temporal_activities_scheduled": 0,
                "inngest_service_started": False,
                "inngest_events_emitted": 0,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "durable_runtime_report_only_scaffolding_packet",
            "label": "Durable Runtime Report-Only Scaffolding Packet",
            "path": DURABLE_RUNTIME_REPORT_ONLY_SCAFFOLDING_PACKET_VALIDATION_JSON,
            "count_key": "packet_component_count",
            "expected": {
                "schema_version": "temporal_inngest_adapter_runtime_report_only_scaffolding_packet_validation.v1",
                "packet_component_count": 5,
                "source_report_only_fixture_count": 5,
                "source_accepted_report_only_fixture_count": 5,
                "fixtures_validation_loaded": True,
                "fixtures_validation_passed": True,
                "preflight_validation_loaded": True,
                "preflight_validation_passed": True,
                "all_packet_components_report_only": True,
                "runtime_implementation_allowed": False,
                "runtime_code_write_allowed": False,
                "report_only_scaffolding_allowed": True,
                "runtime_component_count": 0,
                "runtime_side_effect_component_count": 0,
                "executable_code_component_count": 0,
                "forbidden_runtime_import_count": 0,
                "no_forbidden_runtime_imports_detected": True,
                "model_api_gate_remains_parked": True,
                "model_api_pool_registered": False,
                "all_checks_passed": True,
                "failure_count": 0,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "temporal_server_started": False,
                "temporal_workflows_started": 0,
                "temporal_activities_scheduled": 0,
                "inngest_service_started": False,
                "inngest_events_emitted": 0,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "durable_runtime_report_only_scaffolding_artifacts",
            "label": "Durable Runtime Report-Only Scaffolding Artifacts",
            "path": DURABLE_RUNTIME_REPORT_ONLY_SCAFFOLDING_ARTIFACTS_VALIDATION_JSON,
            "count_key": "materialized_artifact_count",
            "expected": {
                "schema_version": "temporal_inngest_adapter_runtime_report_only_scaffolding_artifacts_validation.v1",
                "materialized_artifact_count": 5,
                "packet_component_count": 5,
                "packet_validation_loaded": True,
                "packet_validation_passed": True,
                "all_materialized_artifacts_report_only": True,
                "markdown_artifact_count": 3,
                "json_artifact_count": 2,
                "json_artifacts_parse": True,
                "executable_artifact_count": 0,
                "runtime_artifact_count": 0,
                "runtime_side_effect_artifact_count": 0,
                "runtime_implementation_allowed": False,
                "runtime_code_write_allowed": False,
                "report_only_scaffolding_allowed": True,
                "forbidden_runtime_import_count": 0,
                "no_forbidden_runtime_imports_detected": True,
                "model_api_gate_remains_parked": True,
                "model_api_pool_registered": False,
                "all_checks_passed": True,
                "failure_count": 0,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "temporal_server_started": False,
                "temporal_workflows_started": 0,
                "temporal_activities_scheduled": 0,
                "inngest_service_started": False,
                "inngest_events_emitted": 0,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["durable_runtime_integrity_specs"]
