from __future__ import annotations

from typing import Any

"""Human-decision service-worker integrity specs."""

from .constants import (
    SERVICE_WORKER_DECISION_AUTHORITY_MATRIX_VALIDATION_JSON,
    SERVICE_WORKER_DECISION_COMMAND_SAFETY_VALIDATION_JSON,
    SERVICE_WORKER_DECISION_DRIFT_VALIDATION_JSON,
    SERVICE_WORKER_DECISION_PREFLIGHT_VALIDATION_JSON,
    SERVICE_WORKER_HUMAN_DECISION_PACKETS_VALIDATION_JSON,
    SERVICE_WORKER_POST_DECISION_REFRESH_PLAN_VALIDATION_JSON,
    SERVICE_WORKER_POST_DECISION_SIMULATION_VALIDATION_JSON,
)


def service_worker_decision_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "human_decision_packets",
            "label": "Human Decision Packets",
            "path": SERVICE_WORKER_HUMAN_DECISION_PACKETS_VALIDATION_JSON,
            "count_key": "decision_packet_count",
            "expected": {
                "schema_version": "service_worker_human_decision_packets_validation.v1",
                "decision_packet_count": 11,
                "terminal_do_not_approve_count": 3,
                "approve_command_preview_count": 11,
                "reject_command_preview_count": 11,
                "failure_count": 0,
                "all_preconditions_for_human_decision_packets": True,
                "all_packets_require_manual_review": True,
                "all_packets_no_approval": True,
                "all_packets_no_registration": True,
                "all_packets_no_assignment": True,
                "approval_granted_by_decision_packets": False,
                "pools_registered_by_decision_packets": 0,
                "service_requests_assigned_by_decision_packets": 0,
                "service_requests_updated_by_decision_packets": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "post_decision_simulation",
            "label": "Post-Decision Simulation",
            "path": SERVICE_WORKER_POST_DECISION_SIMULATION_VALIDATION_JSON,
            "count_key": "simulation_count",
            "expected": {
                "schema_version": "service_worker_post_decision_simulation_validation.v1",
                "simulation_count": 11,
                "branch_count": 22,
                "failure_count": 0,
                "all_no_execution": True,
                "all_input_preconditions_passed": True,
                "approval_granted_by_simulation": False,
                "rejection_granted_by_simulation": False,
                "pools_registered_by_simulation": 0,
                "service_requests_assigned_by_simulation": 0,
                "service_requests_updated_by_simulation": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "post_decision_refresh_plan",
            "label": "Post-Decision Refresh Plan",
            "path": SERVICE_WORKER_POST_DECISION_REFRESH_PLAN_VALIDATION_JSON,
            "count_key": "refresh_plan_count",
            "expected": {
                "schema_version": "service_worker_post_decision_refresh_plan_validation.v1",
                "refresh_plan_count": 11,
                "approval_sequence_count": 11,
                "rejection_sequence_count": 11,
                "approval_command_preview_count": 77,
                "rejection_command_preview_count": 22,
                "command_preview_count": 99,
                "failure_count": 0,
                "all_no_execution": True,
                "all_input_preconditions_passed": True,
                "all_worker_starts_remain_blocked": True,
                "approval_granted_by_refresh_plan": False,
                "rejection_granted_by_refresh_plan": False,
                "refresh_commands_run_by_plan": 0,
                "pools_registered_by_refresh_plan": 0,
                "service_requests_assigned_by_refresh_plan": 0,
                "service_requests_updated_by_refresh_plan": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "decision_drift_guard",
            "label": "Decision Drift Guard",
            "path": SERVICE_WORKER_DECISION_DRIFT_VALIDATION_JSON,
            "count_key": "drift_check_count",
            "expected": {
                "schema_version": "service_worker_decision_drift_guard_validation.v1",
                "drift_check_count": 11,
                "stale_packet_count": 0,
                "status_changed_count": 0,
                "approval_record_count": 0,
                "assigned_count": 0,
                "started_count": 0,
                "completed_count": 0,
                "updated_after_packet_count": 0,
                "recovery_command_preview_count": 55,
                "all_packets_current": True,
                "all_no_execution": True,
                "all_input_preconditions_passed": True,
                "approval_granted_by_drift_guard": False,
                "rejection_granted_by_drift_guard": False,
                "recovery_commands_run_by_drift_guard": 0,
                "pools_registered_by_drift_guard": 0,
                "service_requests_assigned_by_drift_guard": 0,
                "service_requests_updated_by_drift_guard": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "decision_command_safety",
            "label": "Decision Command Safety",
            "path": SERVICE_WORKER_DECISION_COMMAND_SAFETY_VALIDATION_JSON,
            "count_key": "command_review_count",
            "expected": {
                "schema_version": "service_worker_decision_command_safety_validation.v1",
                "command_review_count": 11,
                "approve_command_count": 11,
                "reject_command_count": 11,
                "decision_command_count": 22,
                "approve_placeholder_scope_count": 11,
                "approve_requires_scope_replacement_count": 11,
                "reject_requires_reason_review_count": 11,
                "directly_runnable_approve_count": 0,
                "directly_runnable_reject_count": 0,
                "all_commands_require_manual_review": True,
                "all_approve_commands_require_scope_replacement": True,
                "all_no_execution": True,
                "all_input_preconditions_passed": True,
                "approval_granted_by_command_safety": False,
                "rejection_granted_by_command_safety": False,
                "decision_commands_run_by_safety": 0,
                "pools_registered_by_command_safety": 0,
                "service_requests_assigned_by_command_safety": 0,
                "service_requests_updated_by_command_safety": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "decision_authority_matrix",
            "label": "Decision Authority Matrix",
            "path": SERVICE_WORKER_DECISION_AUTHORITY_MATRIX_VALIDATION_JSON,
            "count_key": "authority_review_count",
            "expected": {
                "schema_version": "service_worker_decision_authority_matrix_validation.v1",
                "authority_review_count": 11,
                "human_user_required_count": 4,
                "cro_required_count": 11,
                "ceo_required_count": 1,
                "reputation_review_required_count": 1,
                "missing_role_count": 0,
                "all_authority_roles_present": True,
                "all_input_preconditions_passed": True,
                "decision_authority_granted_by_matrix": False,
                "approval_granted_by_authority_matrix": False,
                "rejection_granted_by_authority_matrix": False,
                "authority_commands_run_by_matrix": 0,
                "pools_registered_by_authority_matrix": 0,
                "service_requests_assigned_by_authority_matrix": 0,
                "service_requests_updated_by_authority_matrix": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "decision_preflight",
            "label": "Decision Preflight",
            "path": SERVICE_WORKER_DECISION_PREFLIGHT_VALIDATION_JSON,
            "count_key": "preflight_count",
            "expected": {
                "schema_version": "service_worker_decision_preflight_validation.v1",
                "preflight_count": 11,
                "ready_for_human_review_count": 11,
                "preflight_passed_count": 11,
                "blocked_count": 0,
                "execution_allowed_count": 0,
                "assignment_allowed_count": 0,
                "worker_start_allowed_count": 0,
                "all_no_execution": True,
                "all_input_preconditions_passed": True,
                "decision_authority_granted_by_preflight": False,
                "approval_granted_by_preflight": False,
                "rejection_granted_by_preflight": False,
                "pools_registered_by_preflight": 0,
                "service_requests_assigned_by_preflight": 0,
                "service_requests_updated_by_preflight": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["service_worker_decision_integrity_specs"]
