from __future__ import annotations

from typing import Any

"""CEO report-only parser and mutation-preflight integrity specs."""

from .constants import (
    CEO_BLOCKER_TRIAGE_VALIDATION_JSON,
    CEO_DECISION_INTAKE_GUARD_VALIDATION_JSON,
    CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PACKET_DRAFTS_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_DRY_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_DRY_RUN_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_FIXTURE_SUITE_VALIDATION_JSON,
    CEO_DECISION_PARSER_MUTATION_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_VALIDATION_JSON,
    CEO_GATE_BLOCKER_BOARD_VALIDATION_JSON,
)


def ceo_parser_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "ceo_decision_parser_preflight",
            "label": "CEO Decision Parser Preflight",
            "path": CEO_DECISION_PARSER_PREFLIGHT_VALIDATION_JSON,
            "count_key": "preflight_check_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_preflight_validation.v1",
                "preflight_lane_id": "platform_engineering",
                "preflight_task_id": "task-ceo-decision-parser-preflight-20260616",
                "source_fixtures_task_id": "task-ceo-decision-intake-negative-fixtures-20260616",
                "source_fixtures_evidence_id": "ceo-decision-intake-negative-fixtures-20260616",
                "source_negative_fixture_count": 6,
                "source_expected_rejection_count": 6,
                "source_accepted_fixture_count": 0,
                "preflight_check_count": 7,
                "blocking_check_count": 7,
                "parser_implementation_status": "not_implemented",
                "accepted_decision_count": 0,
                "approval_request_count": 0,
                "runnable_without_approval_count": 0,
                "local_decision": "ceo_decision_parser_preflight_ready_parser_not_implemented",
                "recommended_default": "do_not_parse_or_apply_decisions_until_preflight_is_implemented",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 194,
                "tasks_table_rows_after": 195,
                "task_rows_inserted_by_preflight": 1,
                "lane_evidence_rows_before": 102,
                "lane_evidence_rows_after": 103,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_dry_run_contract",
            "label": "CEO Decision Parser Dry-Run Contract",
            "path": CEO_DECISION_PARSER_DRY_RUN_CONTRACT_VALIDATION_JSON,
            "count_key": "contract_section_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_dry_run_contract_validation.v1",
                "contract_lane_id": "platform_engineering",
                "contract_task_id": "task-ceo-decision-parser-dry-run-contract-20260616",
                "source_preflight_task_id": "task-ceo-decision-parser-preflight-20260616",
                "source_preflight_evidence_id": "ceo-decision-parser-preflight-20260616",
                "source_preflight_check_count": 7,
                "source_blocking_check_count": 7,
                "contract_section_count": 6,
                "mutation_preview_state_count": 4,
                "parser_execution_count": 0,
                "accepted_decision_count": 0,
                "approval_request_count": 0,
                "runnable_without_approval_count": 0,
                "local_decision": "ceo_decision_parser_dry_run_contract_ready_parser_not_executed",
                "recommended_default": "report_only_dry_run_before_any_mutation",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 195,
                "tasks_table_rows_after": 196,
                "task_rows_inserted_by_contract": 1,
                "lane_evidence_rows_before": 103,
                "lane_evidence_rows_after": 104,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_positive_fixture",
            "label": "CEO Decision Parser Positive Fixture",
            "path": CEO_DECISION_PARSER_POSITIVE_FIXTURE_VALIDATION_JSON,
            "count_key": "positive_fixture_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_positive_fixture_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-ceo-decision-parser-positive-fixture-20260616",
                "source_contract_task_id": "task-ceo-decision-parser-dry-run-contract-20260616",
                "source_contract_evidence_id": "ceo-decision-parser-dry-run-contract-20260616",
                "source_contract_section_count": 6,
                "source_mutation_preview_state_count": 4,
                "positive_fixture_count": 1,
                "expected_dry_run_preview_count": 1,
                "expected_preview_state": "would_create_bounded_service_request_update",
                "parser_execution_count": 0,
                "accepted_decision_count": 0,
                "approval_request_count": 0,
                "runnable_without_approval_count": 0,
                "local_decision": "ceo_decision_parser_positive_fixture_ready_parser_not_executed",
                "recommended_default": "report_only_dry_run_before_any_mutation",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 196,
                "tasks_table_rows_after": 197,
                "task_rows_inserted_by_fixture": 1,
                "lane_evidence_rows_before": 104,
                "lane_evidence_rows_after": 105,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_fixture_suite",
            "label": "CEO Decision Parser Fixture Suite",
            "path": CEO_DECISION_PARSER_FIXTURE_SUITE_VALIDATION_JSON,
            "count_key": "fixture_suite_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_fixture_suite_validation.v1",
                "suite_lane_id": "platform_engineering",
                "suite_task_id": "task-ceo-decision-parser-fixture-suite-20260616",
                "source_negative_task_id": "task-ceo-decision-intake-negative-fixtures-20260616",
                "source_positive_task_id": "task-ceo-decision-parser-positive-fixture-20260616",
                "negative_fixture_count": 6,
                "positive_fixture_count": 1,
                "fixture_suite_count": 7,
                "expected_rejection_count": 6,
                "expected_dry_run_preview_count": 1,
                "parser_execution_count": 0,
                "accepted_decision_count": 0,
                "approval_request_count": 0,
                "runnable_without_approval_count": 0,
                "local_decision": "ceo_decision_parser_fixture_suite_ready_parser_not_executed",
                "recommended_default": "pass_fixture_suite_before_parser_execution",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 197,
                "tasks_table_rows_after": 198,
                "task_rows_inserted_by_suite": 1,
                "lane_evidence_rows_before": 105,
                "lane_evidence_rows_after": 106,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_report_only_harness",
            "label": "CEO Decision Parser Report-Only Harness",
            "path": CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_VALIDATION_JSON,
            "count_key": "harness_case_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_report_only_harness_validation.v1",
                "harness_lane_id": "platform_engineering",
                "harness_task_id": "task-ceo-decision-parser-report-only-harness-20260616",
                "source_suite_task_id": "task-ceo-decision-parser-fixture-suite-20260616",
                "fixture_suite_count": 7,
                "negative_fixture_count": 6,
                "positive_fixture_count": 1,
                "harness_case_count": 5,
                "required_pass_count": 5,
                "parser_execution_count": 0,
                "accepted_decision_count": 0,
                "approval_request_count": 0,
                "queue_mutation_count": 0,
                "local_decision": "ceo_decision_parser_report_only_harness_ready_parser_not_run",
                "recommended_default": "implement_report_only_parser_against_harness_before_mutations",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 198,
                "tasks_table_rows_after": 199,
                "task_rows_inserted_by_harness": 1,
                "lane_evidence_rows_before": 106,
                "lane_evidence_rows_after": 107,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_report_only_runner",
            "label": "CEO Decision Parser Report-Only Runner",
            "path": CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_VALIDATION_JSON,
            "count_key": "parser_execution_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_report_only_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-ceo-decision-parser-report-only-runner-20260616",
                "source_harness_task_id": "task-ceo-decision-parser-report-only-harness-20260616",
                "fixture_suite_count": 7,
                "negative_fixture_count": 6,
                "positive_fixture_count": 1,
                "parser_execution_count": 7,
                "rejected_decision_count": 6,
                "accepted_dry_run_preview_count": 1,
                "expected_rejection_match_count": 6,
                "expected_preview_match_count": 1,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "local_decision": "ceo_decision_parser_report_only_runner_passed_no_mutations",
                "recommended_default": "keep_parser_report_only_until_operator_approves_mutations",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 199,
                "tasks_table_rows_after": 200,
                "task_rows_inserted_by_runner": 1,
                "lane_evidence_rows_before": 107,
                "lane_evidence_rows_after": 108,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_mutation_preflight",
            "label": "CEO Decision Parser Mutation Preflight",
            "path": CEO_DECISION_PARSER_MUTATION_PREFLIGHT_VALIDATION_JSON,
            "count_key": "candidate_preview_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_mutation_preflight_validation.v1",
                "preflight_lane_id": "platform_engineering",
                "preflight_task_id": "task-ceo-decision-parser-mutation-preflight-20260616",
                "source_runner_task_id": "task-ceo-decision-parser-report-only-runner-20260616",
                "candidate_preview_count": 1,
                "required_approval_field_count": 8,
                "required_blocker_count": 2,
                "forbidden_action_count": 10,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "local_decision": "ceo_decision_parser_mutation_preflight_ready_no_apply",
                "recommended_default": "require_explicit_operator_mutation_approval_before_apply",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 200,
                "tasks_table_rows_after": 201,
                "task_rows_inserted_by_preflight": 1,
                "lane_evidence_rows_before": 108,
                "lane_evidence_rows_after": 109,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["ceo_parser_integrity_specs"]
