from __future__ import annotations

from typing import Any

"""Money-path, paid-code, and digital-product lane integrity specs."""

from .constants import (
    COMPANY_EXPANSION_GAP_MAP_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_VALIDATION_JSON,
    FIRST_LOCAL_EVIDENCE_PACKETS_VALIDATION_JSON,
    FIRST_RANKED_MANAGER_PROOF_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PACKETS_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_PREFLIGHT_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_QUEUE_VALIDATION_JSON,
    MONEY_PATH_COVERAGE_AUDIT_VALIDATION_JSON,
    PAID_CODE_BROWSER_REFRESH_DECISION_PACKET_VALIDATION_JSON,
    PAID_CODE_DUPLICATE_CHECK_WORKSHEET_VALIDATION_JSON,
    PAID_CODE_LOCAL_WORKSHEET_ANSWERS_VALIDATION_JSON,
)


def money_path_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "company_expansion_gap_map",
            "label": "Company Expansion Gap Map",
            "path": COMPANY_EXPANSION_GAP_MAP_VALIDATION_JSON,
            "count_key": "next_test_candidate_count",
            "expected": {
                "schema_version": "agent_company.company_expansion_gap_map_validation.v1",
                "active_lane_count": 12,
                "owned_active_lane_count": 11,
                "read_only_external_owned_lane_count": 1,
                "read_only_boundary_preserved": True,
                "service_catalog_count": 13,
                "source_spec_gap_count": 0,
                "evidence_gap_count": 0,
                "parked_service_request_count": 11,
                "all_active_lanes_scanned": True,
                "all_active_lanes_have_next_test_candidate": True,
                "next_test_candidate_count": 12,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "money_path_coverage_audit",
            "label": "Money Path Coverage Audit",
            "path": MONEY_PATH_COVERAGE_AUDIT_VALIDATION_JSON,
            "count_key": "recommended_next_lane_count",
            "expected": {
                "schema_version": "agent_company.money_path_coverage_audit_validation.v1",
                "active_lane_count": 12,
                "owned_active_lane_count": 11,
                "source_spec_count": 13,
                "thin_evidence_threshold": 1,
                "thin_evidence_lane_count": 0,
                "recommended_next_lane_count": 0,
                "coverage_audit_task_present": True,
                "coverage_audit_evidence_present": True,
                "read_only_boundary_preserved": True,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "first_local_evidence_packets",
            "label": "First Local Evidence Packets",
            "path": FIRST_LOCAL_EVIDENCE_PACKETS_VALIDATION_JSON,
            "count_key": "evidence_packet_count",
            "expected": {
                "schema_version": "agent_company.first_local_evidence_packets_validation.v1",
                "evidence_packet_count": 6,
                "evidence_rows_inserted_or_updated": 6,
                "zero_evidence_lane_count_before": 6,
                "zero_evidence_lane_count_after": 0,
                "all_target_lanes_have_evidence_after": True,
                "all_evidence_packets_local_only": True,
                "all_evidence_rows_present": True,
                "source_spec_gap_count_after": 0,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "manager_proof_task_packets",
            "label": "Manager Proof Task Packets",
            "path": MANAGER_PROOF_TASK_PACKETS_VALIDATION_JSON,
            "count_key": "proof_task_packet_count",
            "expected": {
                "schema_version": "agent_company.manager_proof_task_packets_validation.v1",
                "proof_task_packet_count": 6,
                "parked_lane_count": 6,
                "parked_service_request_count": 9,
                "all_packets_report_only": True,
                "all_packets_have_source_spec": True,
                "all_packets_have_evidence": True,
                "live_tasks_created": 0,
                "tasks_table_rows_before": 140,
                "tasks_table_rows_after": 140,
                "task_rows_inserted_by_packet": 0,
                "source_spec_gap_count": 0,
                "evidence_gap_count": 0,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "manager_proof_task_promotion_preflight",
            "label": "Manager Proof Task Promotion Preflight",
            "path": MANAGER_PROOF_TASK_PROMOTION_PREFLIGHT_VALIDATION_JSON,
            "count_key": "promotion_candidate_count",
            "expected": {
                "schema_version": "agent_company.manager_proof_task_promotion_preflight_validation.v1",
                "proof_task_packet_count": 6,
                "promotion_candidate_count": 6,
                "ready_for_manual_promotion_count": 6,
                "blocked_candidate_count": 0,
                "duplicate_task_id_count": 0,
                "duplicate_duplicate_key_count": 0,
                "all_owner_agents_registered": True,
                "all_lanes_active_and_owned": True,
                "all_source_specs_present": True,
                "all_evidence_present": True,
                "all_referenced_service_requests_parked": True,
                "all_packets_report_only": True,
                "live_tasks_created": 0,
                "tasks_table_rows_before": 141,
                "tasks_table_rows_after": 141,
                "task_rows_inserted_by_preflight": 0,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "manager_proof_task_promotion_queue",
            "label": "Manager Proof Task Promotion Queue",
            "path": MANAGER_PROOF_TASK_PROMOTION_QUEUE_VALIDATION_JSON,
            "count_key": "queue_entry_count",
            "expected": {
                "schema_version": "agent_company.manager_proof_task_promotion_queue_validation.v1",
                "promotion_candidate_count": 6,
                "queue_entry_count": 6,
                "ready_queue_count": 6,
                "blocked_queue_count": 0,
                "first_recommended_lane_id": "paid_code_bounties",
                "first_recommended_task_id": "task-paid_code_bounties-first-local-proof-20260615",
                "all_queue_entries_ready": True,
                "all_queue_entries_have_command_preview": True,
                "all_queue_entries_report_only": True,
                "live_tasks_created": 0,
                "tasks_table_rows_before": 142,
                "tasks_table_rows_after": 142,
                "task_rows_inserted_by_queue": 0,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "first_ranked_manager_proof",
            "label": "First Ranked Manager Proof",
            "path": FIRST_RANKED_MANAGER_PROOF_VALIDATION_JSON,
            "count_key": "proof_artifact_count",
            "expected": {
                "schema_version": "agent_company.first_ranked_manager_proof_validation.v1",
                "queue_first_recommended_lane_id": "paid_code_bounties",
                "queue_first_recommended_task_id": "task-paid_code_bounties-first-local-proof-20260615",
                "proof_lane_id": "paid_code_bounties",
                "proof_task_id": "task-paid_code_bounties-first-local-proof-20260615",
                "proof_artifact_count": 2,
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 143,
                "tasks_table_rows_after": 144,
                "task_rows_inserted_by_proof": 1,
                "lane_evidence_rows_before": 73,
                "lane_evidence_rows_after": 74,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]

