from __future__ import annotations

from typing import Any

"""Write-decision migration integrity specs."""

from .constants import (
    AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON,
    AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON,
    AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON,
)


def migration_write_decision_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "agent_company_migration_decision_parser_write_decision_intake_contract",
            "label": "Agent Company Migration Decision Parser Write Decision Intake Contract",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
            "count_key": "parser_write_decision_intake_contract_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_decision_intake_contract_validation.v1",
                "intake_lane_id": "platform_engineering",
                "intake_task_id": "task-agent-company-migration-decision-parser-write-decision-intake-contract-20260616",
                "source_review_task_id": "task-agent-company-migration-decision-parser-install-decision-runner-review-20260616",
                "parser_write_decision_intake_contract_count": 1,
                "accepted_write_decision_type_count": 4,
                "required_field_count": 9,
                "positive_fixture_count": 4,
                "negative_fixture_count": 8,
                "parser_guard_count": 9,
                "output_state_count": 4,
                "evidence_link_count": 4,
                "local_decision": "agent_company_migration_decision_parser_write_decision_intake_contract_ready_for_report_only_fixture_suite",
                "recommended_default": "build_report_only_parser_write_decision_fixture_suite_next_without_writing_parser",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 245,
                "tasks_table_rows_after": 246,
                "task_rows_inserted_by_parser_write_decision_intake_contract": 1,
                "lane_evidence_rows_before": 153,
                "lane_evidence_rows_after": 154,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_write_decision_fixture_suite",
            "label": "Agent Company Migration Decision Parser Write Decision Fixture Suite",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
            "count_key": "parser_write_decision_fixture_suite_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_decision_fixture_suite_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-agent-company-migration-decision-parser-write-decision-fixture-suite-20260616",
                "source_intake_task_id": "task-agent-company-migration-decision-parser-write-decision-intake-contract-20260616",
                "parser_write_decision_fixture_suite_count": 12,
                "positive_fixture_count": 4,
                "negative_fixture_count": 8,
                "required_field_count": 9,
                "parser_guard_count": 9,
                "output_state_count": 4,
                "fixture_assertion_count": 12,
                "local_decision": "agent_company_migration_decision_parser_write_decision_fixture_suite_ready_for_report_only_runner",
                "recommended_default": "build_report_only_parser_write_decision_runner_next_without_writing_parser",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 246,
                "tasks_table_rows_after": 247,
                "task_rows_inserted_by_parser_write_decision_fixture_suite": 1,
                "lane_evidence_rows_before": 154,
                "lane_evidence_rows_after": 155,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "fixtures_executed": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_write_decision_runner",
            "label": "Agent Company Migration Decision Parser Write Decision Runner",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON,
            "count_key": "parser_write_decision_runner_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_decision_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-agent-company-migration-decision-parser-write-decision-runner-20260616",
                "source_fixture_task_id": "task-agent-company-migration-decision-parser-write-decision-fixture-suite-20260616",
                "parser_write_decision_runner_count": 1,
                "fixture_suite_count": 12,
                "fixtures_evaluated": 12,
                "accepted_result_count": 4,
                "rejected_result_count": 8,
                "passed_fixture_count": 12,
                "failed_fixture_count": 0,
                "parser_guard_count": 9,
                "output_state_count": 4,
                "local_decision": "agent_company_migration_decision_parser_write_decision_runner_ready_for_report_only_parser_write_review",
                "recommended_default": "review_report_only_parser_write_runner_results_next_without_writing_parser",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 247,
                "tasks_table_rows_after": 248,
                "task_rows_inserted_by_parser_write_decision_runner": 1,
                "lane_evidence_rows_before": 155,
                "lane_evidence_rows_after": 156,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "report_only_fixtures_evaluated": True,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_write_decision_runner_review",
            "label": "Agent Company Migration Decision Parser Write Decision Runner Review",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
            "count_key": "parser_write_decision_runner_review_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_decision_runner_review_validation.v1",
                "review_lane_id": "platform_engineering",
                "review_task_id": "task-agent-company-migration-decision-parser-write-decision-runner-review-20260616",
                "source_runner_task_id": "task-agent-company-migration-decision-parser-write-decision-runner-20260616",
                "parser_write_decision_runner_review_count": 1,
                "runner_result_check_count": 6,
                "approval_condition_count": 6,
                "hold_condition_count": 6,
                "evidence_link_count": 4,
                "operator_instruction_count": 6,
                "local_decision": "agent_company_migration_decision_parser_write_decision_runner_review_ready_for_signed_parser_write_or_hold",
                "recommended_default": "hold_without_signed_one_file_parser_write_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 248,
                "tasks_table_rows_after": 249,
                "task_rows_inserted_by_parser_write_decision_runner_review": 1,
                "lane_evidence_rows_before": 156,
                "lane_evidence_rows_after": 157,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_write_approval_request",
            "label": "Agent Company Migration Decision Parser Write Approval Request",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON,
            "count_key": "parser_write_approval_request_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_approval_request_validation.v1",
                "request_lane_id": "platform_engineering",
                "request_task_id": "task-agent-company-migration-decision-parser-write-approval-request-20260616",
                "source_review_task_id": "task-agent-company-migration-decision-parser-write-decision-runner-review-20260616",
                "parser_write_approval_request_count": 1,
                "approval_field_count": 9,
                "boundary_condition_count": 8,
                "refusal_trigger_count": 8,
                "evidence_link_count": 5,
                "operator_instruction_count": 7,
                "local_decision": "agent_company_migration_decision_parser_write_approval_request_ready_for_signed_operator_decision_or_hold",
                "recommended_default": "hold_without_signed_one_file_parser_write_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 249,
                "tasks_table_rows_after": 250,
                "task_rows_inserted_by_parser_write_approval_request": 1,
                "lane_evidence_rows_before": 157,
                "lane_evidence_rows_after": 158,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["migration_write_decision_integrity_specs"]
