from __future__ import annotations

from typing import Any

"""Money-path, paid-code, and digital-product lane integrity specs."""

from .constants import (
    COMPANY_EXPANSION_GAP_MAP_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_VALIDATION_JSON,
    FIRST_LOCAL_EVIDENCE_PACKETS_VALIDATION_JSON,
    FIRST_RANKED_MANAGER_PROOF_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PACKETS_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_PREFLIGHT_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_QUEUE_VALIDATION_JSON,
    MONEY_PATH_COVERAGE_AUDIT_VALIDATION_JSON,
    PAID_CODE_BROWSER_REFRESH_DECISION_PACKET_VALIDATION_JSON,
    PAID_CODE_DUPLICATE_CHECK_WORKSHEET_VALIDATION_JSON,
    PAID_CODE_LOCAL_WORKSHEET_ANSWERS_VALIDATION_JSON,
)



def digital_product_approval_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "digital_products_local_approval_request_drafts",
            "label": "Digital Products Local Approval Request Drafts",
            "path": DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_VALIDATION_JSON,
            "count_key": "draft_packet_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_approval_request_drafts_validation.v1",
                "draft_lane_id": "digital_products_templates_plugins",
                "draft_task_id": "task-digital-products-local-approval-request-drafts-20260616",
                "source_readiness_task_id": "task-digital-products-local-post-polish-readiness-20260616",
                "source_readiness_evidence_id": "digital-products-local-post-polish-readiness-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "draft_packet_count": 2,
                "browser_draft_count": 1,
                "legal_payment_draft_count": 1,
                "approval_request_count": 0,
                "blocked_by_gate_count": 4,
                "local_decision": "approval_request_drafts_ready_not_submitted",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 184,
                "tasks_table_rows_after": 185,
                "task_rows_inserted_by_drafts": 1,
                "lane_evidence_rows_before": 93,
                "lane_evidence_rows_after": 94,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_operator_approval_brief",
            "label": "Digital Products Local Operator Approval Brief",
            "path": DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_VALIDATION_JSON,
            "count_key": "decision_item_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_operator_approval_brief_validation.v1",
                "brief_lane_id": "digital_products_templates_plugins",
                "brief_task_id": "task-digital-products-local-operator-approval-brief-20260616",
                "source_drafts_task_id": "task-digital-products-local-approval-request-drafts-20260616",
                "source_drafts_evidence_id": "digital-products-local-approval-request-drafts-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "decision_item_count": 2,
                "explicit_approval_required_count": 2,
                "approval_request_count": 0,
                "blocked_by_gate_count": 4,
                "local_decision": "operator_approval_brief_ready_not_requested",
                "recommended_default": "hold_until_explicit_user_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 186,
                "tasks_table_rows_after": 187,
                "task_rows_inserted_by_brief": 1,
                "lane_evidence_rows_before": 94,
                "lane_evidence_rows_after": 95,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_post_approval_simulation_plan",
            "label": "Digital Products Local Post-Approval Simulation Plan",
            "path": DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_VALIDATION_JSON,
            "count_key": "simulation_scenario_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_post_approval_simulation_plan_validation.v1",
                "plan_lane_id": "digital_products_templates_plugins",
                "plan_task_id": "task-digital-products-local-post-approval-simulation-plan-20260616",
                "source_brief_task_id": "task-digital-products-local-operator-approval-brief-20260616",
                "source_brief_evidence_id": "digital-products-local-operator-approval-brief-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "simulation_scenario_count": 2,
                "requires_explicit_approval_count": 2,
                "approval_request_count": 0,
                "blocked_by_gate_count": 4,
                "local_decision": "post_approval_simulation_plan_ready_not_executed",
                "recommended_default": "hold_until_explicit_user_approval",
                "simulated_browser_sessions": 0,
                "simulated_legal_payment_reviews": 0,
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 187,
                "tasks_table_rows_after": 188,
                "task_rows_inserted_by_plan": 1,
                "lane_evidence_rows_before": 95,
                "lane_evidence_rows_after": 96,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_gated_hold_register",
            "label": "Digital Products Local Gated Hold Register",
            "path": DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_VALIDATION_JSON,
            "count_key": "hold_entry_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_gated_hold_register_validation.v1",
                "register_lane_id": "digital_products_templates_plugins",
                "register_task_id": "task-digital-products-local-gated-hold-register-20260616",
                "source_plan_task_id": "task-digital-products-local-post-approval-simulation-plan-20260616",
                "source_plan_evidence_id": "digital-products-local-post-approval-simulation-plan-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "hold_entry_count": 4,
                "source_simulation_scenario_count": 2,
                "active_hold_count": 4,
                "explicit_approval_required_count": 4,
                "runnable_without_approval_count": 0,
                "approval_request_count": 0,
                "blocked_by_gate_count": 4,
                "local_decision": "gated_hold_register_active",
                "recommended_default": "hold_until_explicit_user_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 188,
                "tasks_table_rows_after": 189,
                "task_rows_inserted_by_register": 1,
                "lane_evidence_rows_before": 96,
                "lane_evidence_rows_after": 97,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]
