from __future__ import annotations

from typing import Any

"""CEO apply-readiness flow integrity specs."""

from .constants import (
    CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON,
)


def ceo_readiness_flow_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            'id': 'ceo_decision_parser_apply_readiness',
            'label': 'CEO Decision Parser Apply Readiness',
            'path': CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON,
            'count_key': 'readiness_packet_count',
            'expected': {
                'schema_version': 'agent_company.ceo_decision_parser_apply_readiness_validation.v1',
                'readiness_lane_id': 'platform_engineering',
                'readiness_task_id': 'task-ceo-decision-parser-apply-readiness-20260616',
                'source_dry_runner_task_id': 'task-ceo-decision-parser-apply-dry-runner-20260616',
                'readiness_packet_count': 1,
                'target_service_request_count': 1,
                'planned_field_update_count': 2,
                'rollback_check_count': 4,
                'required_operator_approval_count': 5,
                'mutation_applied_count': 0,
                'queue_mutation_count': 0,
                'approval_request_count': 0,
                'target_status_before': 'needs_review',
                'target_status_after': 'needs_review',
                'local_decision': 'ceo_decision_parser_apply_readiness_ready_no_apply',
                'recommended_default': 'hold_for_explicit_operator_apply_approval',
                'live_tasks_created': 1,
                'live_tasks_completed': 1,
                'tasks_table_rows_before': 205,
                'tasks_table_rows_after': 206,
                'task_rows_inserted_by_readiness': 1,
                'lane_evidence_rows_before': 113,
                'lane_evidence_rows_after': 114,
                'evidence_rows_inserted_or_updated': 1,
                'all_checks_passed': True,
                'failure_count': 0,
                'browser_sessions_started': 0,
                'account_actions': False,
                'wallet_actions': False,
                'payment_actions': False,
                'public_actions': False,
                'security_testing_actions': False,
                'real_money_actions': False,
                'service_requests_updated': 0,
                'service_requests_assigned': 0,
                'worker_starts': 0,
                'api_calls': False,
                'external_side_effects': False,
            },
        },
        {
            'id': 'ceo_decision_parser_apply_readiness_negative_fixtures',
            'label': 'CEO Decision Parser Apply Readiness Negative Fixtures',
            'path': CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON,
            'count_key': 'negative_readiness_fixture_count',
            'expected': {
                'schema_version': 'agent_company.ceo_decision_parser_apply_readiness_negative_fixtures_validation.v1',
                'fixture_lane_id': 'platform_engineering',
                'fixture_task_id': 'task-ceo-decision-parser-apply-readiness-negative-fixtures-20260616',
                'source_readiness_task_id': 'task-ceo-decision-parser-apply-readiness-20260616',
                'negative_readiness_fixture_count': 6,
                'expected_rejection_count': 6,
                'accepted_readiness_count': 0,
                'required_readiness_field_count': 6,
                'mutation_applied_count': 0,
                'queue_mutation_count': 0,
                'approval_request_count': 0,
                'local_decision': 'ceo_decision_parser_apply_readiness_negative_fixtures_ready',
                'recommended_default': 'reject_apply_readiness_when_packet_or_target_state_drifts',
                'live_tasks_created': 1,
                'live_tasks_completed': 1,
                'tasks_table_rows_before': 206,
                'tasks_table_rows_after': 207,
                'task_rows_inserted_by_fixtures': 1,
                'lane_evidence_rows_before': 114,
                'lane_evidence_rows_after': 115,
                'evidence_rows_inserted_or_updated': 1,
                'all_checks_passed': True,
                'failure_count': 0,
                'browser_sessions_started': 0,
                'account_actions': False,
                'wallet_actions': False,
                'payment_actions': False,
                'public_actions': False,
                'security_testing_actions': False,
                'real_money_actions': False,
                'service_requests_updated': 0,
                'service_requests_assigned': 0,
                'worker_starts': 0,
                'api_calls': False,
                'external_side_effects': False,
            },
        },
        {
            'id': 'ceo_decision_parser_apply_readiness_guard_runner',
            'label': 'CEO Decision Parser Apply Readiness Guard Runner',
            'path': CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON,
            'count_key': 'readiness_guard_execution_count',
            'expected': {
                'schema_version': 'agent_company.ceo_decision_parser_apply_readiness_guard_runner_validation.v1',
                'runner_lane_id': 'platform_engineering',
                'runner_task_id': 'task-ceo-decision-parser-apply-readiness-guard-runner-20260616',
                'source_fixtures_task_id': 'task-ceo-decision-parser-apply-readiness-negative-fixtures-20260616',
                'negative_readiness_fixture_count': 6,
                'readiness_guard_execution_count': 6,
                'rejected_readiness_count': 6,
                'accepted_readiness_count': 0,
                'expected_rejection_match_count': 6,
                'mutation_applied_count': 0,
                'queue_mutation_count': 0,
                'approval_request_count': 0,
                'local_decision': 'ceo_decision_parser_apply_readiness_guard_runner_passed_no_mutations',
                'recommended_default': 'keep_apply_disabled_until_readiness_guard_passes_and_operator_approves',
                'live_tasks_created': 1,
                'live_tasks_completed': 1,
                'tasks_table_rows_before': 207,
                'tasks_table_rows_after': 208,
                'task_rows_inserted_by_runner': 1,
                'lane_evidence_rows_before': 115,
                'lane_evidence_rows_after': 116,
                'evidence_rows_inserted_or_updated': 1,
                'all_checks_passed': True,
                'failure_count': 0,
                'browser_sessions_started': 0,
                'account_actions': False,
                'wallet_actions': False,
                'payment_actions': False,
                'public_actions': False,
                'security_testing_actions': False,
                'real_money_actions': False,
                'service_requests_updated': 0,
                'service_requests_assigned': 0,
                'worker_starts': 0,
                'api_calls': False,
                'external_side_effects': False,
            },
        },
        {
            'id': 'ceo_decision_parser_apply_readiness_positive_fixture',
            'label': 'CEO Decision Parser Apply Readiness Positive Fixture',
            'path': CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON,
            'count_key': 'positive_readiness_fixture_count',
            'expected': {
                'schema_version': 'agent_company.ceo_decision_parser_apply_readiness_positive_fixture_validation.v1',
                'fixture_lane_id': 'platform_engineering',
                'fixture_task_id': 'task-ceo-decision-parser-apply-readiness-positive-fixture-20260616',
                'source_guard_runner_task_id': 'task-ceo-decision-parser-apply-readiness-guard-runner-20260616',
                'positive_readiness_fixture_count': 1,
                'target_service_request_count': 1,
                'planned_field_update_count': 2,
                'rollback_check_count': 4,
                'required_operator_approval_count': 5,
                'mutation_applied_count': 0,
                'queue_mutation_count': 0,
                'approval_request_count': 0,
                'target_status_before': 'needs_review',
                'target_status_after': 'needs_review',
                'local_decision': 'ceo_decision_parser_apply_readiness_positive_fixture_ready_preview_only',
                'recommended_default': 'positive_readiness_fixture_requires_separate_apply_runner',
                'live_tasks_created': 1,
                'live_tasks_completed': 1,
                'tasks_table_rows_before': 208,
                'tasks_table_rows_after': 209,
                'task_rows_inserted_by_fixture': 1,
                'lane_evidence_rows_before': 116,
                'lane_evidence_rows_after': 117,
                'evidence_rows_inserted_or_updated': 1,
                'all_checks_passed': True,
                'failure_count': 0,
                'browser_sessions_started': 0,
                'account_actions': False,
                'wallet_actions': False,
                'payment_actions': False,
                'public_actions': False,
                'security_testing_actions': False,
                'real_money_actions': False,
                'service_requests_updated': 0,
                'service_requests_assigned': 0,
                'worker_starts': 0,
                'api_calls': False,
                'external_side_effects': False,
            },
        },
        {
            'id': 'ceo_decision_parser_apply_readiness_positive_runner',
            'label': 'CEO Decision Parser Apply Readiness Positive Runner',
            'path': CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON,
            'count_key': 'readiness_guard_execution_count',
            'expected': {
                'schema_version': 'agent_company.ceo_decision_parser_apply_readiness_positive_runner_validation.v1',
                'runner_lane_id': 'platform_engineering',
                'runner_task_id': 'task-ceo-decision-parser-apply-readiness-positive-runner-20260616',
                'source_fixture_task_id': 'task-ceo-decision-parser-apply-readiness-positive-fixture-20260616',
                'positive_readiness_fixture_count': 1,
                'target_service_request_count': 1,
                'planned_field_update_count': 2,
                'rollback_check_count': 4,
                'required_operator_approval_count': 5,
                'readiness_guard_execution_count': 1,
                'accepted_readiness_count': 1,
                'rejected_readiness_count': 0,
                'expected_acceptance_match_count': 1,
                'preview_state_match_count': 1,
                'real_mutation_allowed_count': 0,
                'mutation_applied_count': 0,
                'queue_mutation_count': 0,
                'approval_request_count': 0,
                'target_status_before': 'needs_review',
                'target_status_after': 'needs_review',
                'local_decision': 'ceo_decision_parser_apply_readiness_positive_runner_passed_preview_only',
                'recommended_default': 'positive_runner_still_requires_separate_operator_apply_approval',
                'live_tasks_created': 1,
                'live_tasks_completed': 1,
                'tasks_table_rows_before': 209,
                'tasks_table_rows_after': 210,
                'task_rows_inserted_by_runner': 1,
                'lane_evidence_rows_before': 117,
                'lane_evidence_rows_after': 118,
                'evidence_rows_inserted_or_updated': 1,
                'all_checks_passed': True,
                'failure_count': 0,
                'browser_sessions_started': 0,
                'account_actions': False,
                'wallet_actions': False,
                'payment_actions': False,
                'public_actions': False,
                'security_testing_actions': False,
                'real_money_actions': False,
                'service_requests_updated': 0,
                'service_requests_assigned': 0,
                'worker_starts': 0,
                'api_calls': False,
                'external_side_effects': False,
            },
        }
    ]


__all__ = ["ceo_readiness_flow_integrity_specs"]
