from __future__ import annotations

from typing import Any

"""Decision intake and parser-module migration integrity specs."""

from .constants import (
    AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON,
    AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON,
    AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON,
)


def migration_decision_fixture_integrity_specs() -> list[dict[str, Any]]:
    return [        {
            "id": "agent_company_migration_decision_intake_contract",
            "label": "Agent Company Migration Decision Intake Contract",
            "path": AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
            "count_key": "decision_intake_contract_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_intake_contract_validation.v1",
                "intake_lane_id": "platform_engineering",
                "intake_task_id": "task-agent-company-migration-decision-intake-contract-20260616",
                "source_review_task_id": "task-agent-company-migration-operator-review-20260616",
                "decision_intake_contract_count": 1,
                "accepted_decision_type_count": 4,
                "required_field_count": 8,
                "positive_fixture_count": 4,
                "negative_fixture_count": 8,
                "parser_guard_count": 9,
                "output_state_count": 4,
                "local_decision": "agent_company_migration_decision_intake_contract_ready_for_report_only_fixture_suite",
                "recommended_default": "build_report_only_fixture_suite_next_without_applying_operator_decision",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 231,
                "tasks_table_rows_after": 232,
                "task_rows_inserted_by_intake_contract": 1,
                "lane_evidence_rows_before": 139,
                "lane_evidence_rows_after": 140,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_fixture_suite",
            "label": "Agent Company Migration Decision Fixture Suite",
            "path": AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
            "count_key": "fixture_suite_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_fixture_suite_validation.v1",
                "suite_lane_id": "platform_engineering",
                "suite_task_id": "task-agent-company-migration-decision-fixture-suite-20260616",
                "source_intake_task_id": "task-agent-company-migration-decision-intake-contract-20260616",
                "fixture_suite_count": 12,
                "positive_fixture_count": 4,
                "negative_fixture_count": 8,
                "expected_accept_count": 4,
                "expected_reject_count": 8,
                "parser_guard_count": 9,
                "output_state_count": 4,
                "local_decision": "agent_company_migration_decision_fixture_suite_ready_for_report_only_runner",
                "recommended_default": "build_report_only_fixture_runner_next_without_parsing_live_decisions",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 232,
                "tasks_table_rows_after": 233,
                "task_rows_inserted_by_fixture_suite": 1,
                "lane_evidence_rows_before": 140,
                "lane_evidence_rows_after": 141,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "fixtures_executed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_fixture_runner",
            "label": "Agent Company Migration Decision Fixture Runner",
            "path": AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON,
            "count_key": "fixture_runner_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_fixture_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-agent-company-migration-decision-fixture-runner-20260616",
                "source_suite_task_id": "task-agent-company-migration-decision-fixture-suite-20260616",
                "fixture_runner_count": 1,
                "fixture_suite_count": 12,
                "fixtures_evaluated": 12,
                "accepted_result_count": 4,
                "rejected_result_count": 8,
                "passed_fixture_count": 12,
                "failed_fixture_count": 0,
                "parser_guard_count": 9,
                "output_state_count": 4,
                "local_decision": "agent_company_migration_decision_fixture_runner_ready_for_report_only_parser_scaffold",
                "recommended_default": "build_report_only_parser_scaffold_next_without_parsing_live_decisions",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 233,
                "tasks_table_rows_after": 234,
                "task_rows_inserted_by_fixture_runner": 1,
                "lane_evidence_rows_before": 141,
                "lane_evidence_rows_after": 142,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "report_only_fixtures_evaluated": True,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["migration_decision_fixture_integrity_specs"]
