from __future__ import annotations

from typing import Any

"""CEO blocker board and decision-intake integrity specs."""

from .constants import (
    CEO_BLOCKER_TRIAGE_VALIDATION_JSON,
    CEO_DECISION_INTAKE_GUARD_VALIDATION_JSON,
    CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PACKET_DRAFTS_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_DRY_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_DRY_RUN_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_FIXTURE_SUITE_VALIDATION_JSON,
    CEO_DECISION_PARSER_MUTATION_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_VALIDATION_JSON,
    CEO_GATE_BLOCKER_BOARD_VALIDATION_JSON,
)


def ceo_intake_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "ceo_gate_blocker_board",
            "label": "CEO Gate Blocker Board",
            "path": CEO_GATE_BLOCKER_BOARD_VALIDATION_JSON,
            "count_key": "active_blocker_count",
            "expected": {
                "schema_version": "agent_company.ceo_gate_blocker_board_validation.v1",
                "board_lane_id": "platform_engineering",
                "board_task_id": "task-ceo-gate-blocker-board-20260616",
                "source_register_task_id": "task-digital-products-local-gated-hold-register-20260616",
                "source_register_evidence_id": "digital-products-local-gated-hold-register-20260616",
                "service_request_total_count": 14,
                "service_request_needs_review_count": 11,
                "service_request_rejected_count": 2,
                "service_request_complete_count": 1,
                "active_hold_count": 4,
                "active_blocker_count": 15,
                "active_blocker_lane_count": 7,
                "runnable_without_approval_count": 0,
                "approval_request_count": 0,
                "local_decision": "ceo_gate_blocker_board_current",
                "recommended_default": "hold_all_gated_work_until_explicit_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 189,
                "tasks_table_rows_after": 190,
                "task_rows_inserted_by_board": 1,
                "lane_evidence_rows_before": 97,
                "lane_evidence_rows_after": 98,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_blocker_triage",
            "label": "CEO Blocker Triage",
            "path": CEO_BLOCKER_TRIAGE_VALIDATION_JSON,
            "count_key": "triage_batch_count",
            "expected": {
                "schema_version": "agent_company.ceo_blocker_triage_validation.v1",
                "triage_lane_id": "platform_engineering",
                "triage_task_id": "task-ceo-blocker-triage-20260616",
                "source_board_task_id": "task-ceo-gate-blocker-board-20260616",
                "source_board_evidence_id": "ceo-gate-blocker-board-20260616",
                "source_active_blocker_count": 15,
                "triage_batch_count": 5,
                "high_leverage_batch_count": 3,
                "service_request_needs_review_count": 11,
                "active_hold_count": 4,
                "approval_request_count": 0,
                "runnable_without_approval_count": 0,
                "local_decision": "ceo_blocker_triage_ready_for_human_review",
                "recommended_default": "hold_all_gated_work_until_explicit_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 190,
                "tasks_table_rows_after": 191,
                "task_rows_inserted_by_triage": 1,
                "lane_evidence_rows_before": 98,
                "lane_evidence_rows_after": 99,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_packet_drafts",
            "label": "CEO Decision Packet Drafts",
            "path": CEO_DECISION_PACKET_DRAFTS_VALIDATION_JSON,
            "count_key": "packet_draft_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_packet_drafts_validation.v1",
                "draft_lane_id": "platform_engineering",
                "draft_task_id": "task-ceo-decision-packet-drafts-20260616",
                "source_triage_task_id": "task-ceo-blocker-triage-20260616",
                "source_triage_evidence_id": "ceo-blocker-triage-20260616",
                "source_active_blocker_count": 15,
                "source_triage_batch_count": 5,
                "source_high_leverage_batch_count": 3,
                "packet_draft_count": 3,
                "decision_option_count": 9,
                "approval_request_count": 0,
                "runnable_without_approval_count": 0,
                "local_decision": "ceo_decision_packet_drafts_ready_not_submitted",
                "recommended_default": "hold_all_gated_work_until_explicit_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 191,
                "tasks_table_rows_after": 192,
                "task_rows_inserted_by_drafts": 1,
                "lane_evidence_rows_before": 99,
                "lane_evidence_rows_after": 100,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_intake_guard",
            "label": "CEO Decision Intake Guard",
            "path": CEO_DECISION_INTAKE_GUARD_VALIDATION_JSON,
            "count_key": "required_field_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_intake_guard_validation.v1",
                "guard_lane_id": "platform_engineering",
                "guard_task_id": "task-ceo-decision-intake-guard-20260616",
                "source_drafts_task_id": "task-ceo-decision-packet-drafts-20260616",
                "source_drafts_evidence_id": "ceo-decision-packet-drafts-20260616",
                "source_packet_draft_count": 3,
                "source_decision_option_count": 9,
                "required_field_count": 8,
                "invalid_decision_rule_count": 6,
                "accepted_decision_count": 0,
                "approval_request_count": 0,
                "runnable_without_approval_count": 0,
                "local_decision": "ceo_decision_intake_guard_ready_no_decisions_accepted",
                "recommended_default": "reject_ambiguous_or_unscoped_decisions",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 192,
                "tasks_table_rows_after": 193,
                "task_rows_inserted_by_guard": 1,
                "lane_evidence_rows_before": 100,
                "lane_evidence_rows_after": 101,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_intake_negative_fixtures",
            "label": "CEO Decision Intake Negative Fixtures",
            "path": CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_VALIDATION_JSON,
            "count_key": "negative_fixture_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_intake_negative_fixtures_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-ceo-decision-intake-negative-fixtures-20260616",
                "source_guard_task_id": "task-ceo-decision-intake-guard-20260616",
                "source_guard_evidence_id": "ceo-decision-intake-guard-20260616",
                "source_required_field_count": 8,
                "source_invalid_decision_rule_count": 6,
                "negative_fixture_count": 6,
                "expected_rejection_count": 6,
                "accepted_fixture_count": 0,
                "approval_request_count": 0,
                "runnable_without_approval_count": 0,
                "local_decision": "ceo_decision_intake_negative_fixtures_ready",
                "recommended_default": "reject_ambiguous_or_unscoped_decisions",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 193,
                "tasks_table_rows_after": 194,
                "task_rows_inserted_by_fixtures": 1,
                "lane_evidence_rows_before": 101,
                "lane_evidence_rows_after": 102,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["ceo_intake_integrity_specs"]
