from __future__ import annotations

from typing import Any

"""Runtime implementation, sandbox, DAG, dispatch, and worker-pool integrity specs."""

from .constants import (
    DURABLE_ORCHESTRATION_DIR,
)
from .paths import REPORTS_DIR


def runtime_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "local_service_worker_request_state_machine_runner",
            "label": "Local Service-Worker Request State-Machine Runner",
            "path": (
                DURABLE_ORCHESTRATION_DIR
                / "local-service-worker-request-state-machine-runner-v1-validation-20260617.json"
            ),
            "count_key": "transition_count",
            "expected": {
                "schema_version": "agent_company.local_service_worker_request_state_machine_runner_validation.v1",
                "transition_count": 14,
                "policy_probe_count": 5,
                "status_counts": {
                    "complete": 1,
                    "needs_review": 11,
                    "rejected": 2,
                },
                "disposition_counts": {
                    "parked_awaiting_human_review": 11,
                    "terminal_noop": 3,
                },
                "failed_count": 0,
            },
        },
        {
            "id": "runtime_implementation_human_approval_packet_v2",
            "label": "Runtime Implementation Human Approval Packet v2",
            "path": (
                DURABLE_ORCHESTRATION_DIR
                / "runtime-implementation-human-approval-packet-v2-validation-20260617.json"
            ),
            "count_key": "approval_question_count",
            "expected": {
                "schema_version": "agent_company.runtime_implementation_human_approval_packet_v2_validation.v1",
                "all_checks_passed": True,
                "failure_count": 0,
                "runtime_candidate_count": 7,
                "approval_question_count": 12,
                "required_decision_field_count": 16,
                "source_runner_validation_count": 3,
                "source_runner_failure_count": 0,
                "approval_granted_by_packet": False,
                "runtime_implementation_allowed": False,
                "runtime_code_write_allowed": False,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "runtime_starts": 0,
                "server_starts": 0,
                "database_provisioning": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "browser_sessions_started": 0,
                "api_calls": False,
                "model_api_calls": False,
                "public_actions": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "runtime_implementation_signed_decision_guard_v1",
            "label": "Runtime Implementation Signed Decision Guard v1",
            "path": (
                DURABLE_ORCHESTRATION_DIR
                / "runtime-implementation-signed-decision-guard-v1-validation-20260617.json"
            ),
            "count_key": "fixture_count",
            "expected": {
                "schema_version": "agent_company.runtime_implementation_signed_decision_guard_validation.v1",
                "all_checks_passed": True,
                "failure_count": 0,
                "fixture_count": 19,
                "accepted_count": 2,
                "rejected_count": 17,
                "expected_accepted_count": 2,
                "expected_rejected_count": 17,
                "decisions_applied": 0,
                "approval_rows_written": 0,
                "runtime_implementation_allowed": False,
                "runtime_code_write_allowed": False,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "runtime_starts": 0,
                "server_starts": 0,
                "database_provisioning": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "service_requests_started": 0,
                "worker_starts": 0,
                "browser_sessions_started": 0,
                "api_calls": False,
                "model_api_calls": False,
                "public_actions": False,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "runtime_implementation_apply_preflight_blocker_v1",
            "label": "Runtime Implementation Apply Preflight Blocker v1",
            "path": (
                DURABLE_ORCHESTRATION_DIR
                / "runtime-implementation-apply-preflight-blocker-v1-validation-20260617.json"
            ),
            "count_key": "preflight_check_count",
            "expected": {
                "schema_version": "agent_company.runtime_implementation_apply_preflight_blocker_validation.v1",
                "all_checks_passed": True,
                "failure_count": 0,
                "preflight_check_count": 6,
                "accepted_guard_decision_count": 2,
                "rejected_guard_decision_count": 17,
                "fixture_decisions_apply_blocked": True,
                "real_decision_required": True,
                "real_signed_decision_present": False,
                "apply_allowed": False,
                "runtime_implementation_allowed": False,
                "runtime_code_write_allowed": False,
                "apply_commands_written": 0,
                "apply_commands_executed": 0,
                "decisions_applied": 0,
                "approval_rows_written": 0,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "runtime_starts": 0,
                "server_starts": 0,
                "database_provisioning": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "service_requests_started": 0,
                "worker_starts": 0,
                "browser_sessions_started": 0,
                "api_calls": False,
                "model_api_calls": False,
                "public_actions": False,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "sandbox_execution_gate_contract_v1",
            "label": "Sandbox Execution Gate Contract v1",
            "path": REPORTS_DIR / "sandbox-execution-gate-contract-v1-validation-20260617.json",
            "count_key": "negative_probe_count",
            "expected": {
                "schema_version": "agent_company.sandbox_execution_gate_contract_validation.v1",
                "all_checks_passed": True,
                "failure_count": 0,
                "candidate_pattern_count": 2,
                "required_approval_field_count": 18,
                "hard_deny_count": 10,
                "negative_probe_count": 10,
                "negative_probe_rejected_count": 10,
                "sandbox_sessions_started": 0,
                "processes_started": 0,
                "commands_executed": 0,
                "files_written_outside_workspace": 0,
                "network_enabled": False,
                "secrets_read": False,
                "api_keys_used": False,
                "cloud_sandbox_started": False,
                "dependency_installs": 0,
                "dependency_imports": 0,
                "runtime_starts": 0,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "browser_sessions_started": 0,
                "model_api_calls": False,
                "public_actions": False,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_task_dag_contract_v1",
            "label": "Agent Task DAG Contract v1",
            "path": REPORTS_DIR / "agent-task-dag-contract-v1-validation-20260617.json",
            "count_key": "node_count",
            "expected": {
                "schema_version": "agent_company.agent_task_dag_contract_validation.v1",
                "all_checks_passed": True,
                "failure_count": 0,
                "node_count": 10,
                "edge_count": 12,
                "gate_count": 3,
                "evidence_requirement_count": 3,
                "approves_actions": False,
                "starts_workers": False,
                "updates_service_requests": False,
                "calls_apis": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_dispatch_batch_v1",
            "label": "CEO Dispatch Batch v1",
            "path": REPORTS_DIR / "ceo-dispatch-batch-v1-validation-20260617.json",
            "count_key": "entry_count",
            "expected": {
                "schema_version": "agent_company.ceo_dispatch_batch_validation.v1",
                "all_checks_passed": True,
                "failure_count": 0,
                "entry_count": 10,
                "completed_foundation_count": 3,
                "ready_local_dispatch_count": 2,
                "blocked_by_gate_count": 4,
                "waiting_on_dependencies_count": 1,
                "creates_tasks": False,
                "approves_actions": False,
                "starts_workers": False,
                "updates_service_requests": False,
                "calls_apis": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "worker_pool_assignment_preflight_v1",
            "label": "Worker Pool Assignment Preflight v1",
            "path": REPORTS_DIR / "worker-pool-assignment-preflight-v1-validation-20260617.json",
            "count_key": "assignment_plan_count",
            "expected": {
                "schema_version": "agent_company.worker_pool_assignment_preflight_validation.v1",
                "all_checks_passed": True,
                "failure_count": 0,
                "assignment_plan_count": 14,
                "assignable_now_count": 0,
                "pool_count": 7,
                "missing_pool_count": 7,
                "readiness_request_count": 14,
                "ready_to_start_count": 0,
                "human_cro_gate_count": 11,
                "terminal_no_execution_count": 3,
                "blocker_count": 4,
                "allowed_now_count": 2,
                "blocked_action_count": 2,
                "registers_pools": False,
                "assigns_service_requests": False,
                "starts_workers": False,
                "updates_service_requests": False,
                "calls_apis": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "worker_pool_registration_review_v1",
            "label": "Worker Pool Registration Review v1",
            "path": REPORTS_DIR / "worker-pool-registration-review-v1-validation-20260617.json",
            "count_key": "packet_count",
            "expected": {
                "schema_version": "agent_company.worker_pool_registration_review_validation.v1",
                "all_checks_passed": True,
                "failure_count": 0,
                "packet_count": 7,
                "high_priority_count": 2,
                "manual_register_later_count": 5,
                "manual_hold_count": 2,
                "commands_executed": 0,
                "registers_pools": False,
                "assigns_service_requests": False,
                "starts_workers": False,
                "updates_service_requests": False,
                "calls_apis": False,
                "external_side_effects": False,
            },
        },
    ]
