from __future__ import annotations

from typing import Any

"""Money-path, paid-code, and digital-product lane integrity specs."""

from .constants import (
    COMPANY_EXPANSION_GAP_MAP_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_VALIDATION_JSON,
    FIRST_LOCAL_EVIDENCE_PACKETS_VALIDATION_JSON,
    FIRST_RANKED_MANAGER_PROOF_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PACKETS_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_PREFLIGHT_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_QUEUE_VALIDATION_JSON,
    MONEY_PATH_COVERAGE_AUDIT_VALIDATION_JSON,
    PAID_CODE_BROWSER_REFRESH_DECISION_PACKET_VALIDATION_JSON,
    PAID_CODE_DUPLICATE_CHECK_WORKSHEET_VALIDATION_JSON,
    PAID_CODE_LOCAL_WORKSHEET_ANSWERS_VALIDATION_JSON,
)



def digital_product_demand_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "digital_products_local_demand_proof",
            "label": "Digital Products Local Demand Proof",
            "path": DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_VALIDATION_JSON,
            "count_key": "proof_question_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_demand_proof_validation.v1",
                "proof_lane_id": "digital_products_templates_plugins",
                "proof_task_id": "task-digital_products_templates_plugins-first-local-proof-20260615",
                "source_spec_id": "digital_products_marketplace_demand_source_seed",
                "parked_service_request_count": 3,
                "proof_question_count": 8,
                "blocked_by_gate_count": 4,
                "local_only_question_count": 4,
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 150,
                "tasks_table_rows_after": 151,
                "task_rows_inserted_by_proof": 1,
                "lane_evidence_rows_before": 76,
                "lane_evidence_rows_after": 77,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_demand_memo",
            "label": "Digital Products Local Demand Memo",
            "path": DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_VALIDATION_JSON,
            "count_key": "memo_section_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_demand_memo_validation.v1",
                "memo_lane_id": "digital_products_templates_plugins",
                "memo_task_id": "task-digital-products-local-demand-memo-20260615",
                "source_proof_task_id": "task-digital_products_templates_plugins-first-local-proof-20260615",
                "source_proof_evidence_id": "digital-products-local-demand-proof-20260615",
                "parked_service_request_count": 3,
                "memo_section_count": 6,
                "candidate_count": 3,
                "blocked_by_gate_count": 4,
                "local_decision": "prepare_build_brief_no_live_marketplace_action",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 152,
                "tasks_table_rows_after": 153,
                "task_rows_inserted_by_memo": 1,
                "lane_evidence_rows_before": 77,
                "lane_evidence_rows_after": 78,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_build_brief",
            "label": "Digital Products Local Build Brief",
            "path": DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_VALIDATION_JSON,
            "count_key": "build_section_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_build_brief_validation.v1",
                "brief_lane_id": "digital_products_templates_plugins",
                "brief_task_id": "task-digital-products-local-build-brief-20260616",
                "source_memo_task_id": "task-digital-products-local-demand-memo-20260615",
                "source_memo_evidence_id": "digital-products-local-demand-memo-20260615",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "parked_service_request_count": 3,
                "build_section_count": 7,
                "deliverable_count": 6,
                "acceptance_criterion_count": 5,
                "blocked_by_gate_count": 4,
                "local_decision": "draft_assets_locally_no_listing_or_marketplace_action",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 154,
                "tasks_table_rows_after": 155,
                "task_rows_inserted_by_brief": 1,
                "lane_evidence_rows_before": 78,
                "lane_evidence_rows_after": 79,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]
