from __future__ import annotations

from typing import Any

"""CEO signed apply-command integrity specs."""

from .constants import (
    CEO_BLOCKER_TRIAGE_VALIDATION_JSON,
    CEO_DECISION_INTAKE_GUARD_VALIDATION_JSON,
    CEO_DECISION_INTAKE_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PACKET_DRAFTS_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_DRY_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_DECISION_INTAKE_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_NO_APPROVAL_BLOCKER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_OPERATOR_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_GUARD_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_NEGATIVE_FIXTURES_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_OPERATOR_APPLY_APPROVAL_PACKET_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_POSITIVE_RUNNER_VALIDATION_JSON,
    CEO_DECISION_PARSER_APPLY_READINESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_DRY_RUN_CONTRACT_VALIDATION_JSON,
    CEO_DECISION_PARSER_FIXTURE_SUITE_VALIDATION_JSON,
    CEO_DECISION_PARSER_MUTATION_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_POSITIVE_FIXTURE_VALIDATION_JSON,
    CEO_DECISION_PARSER_PREFLIGHT_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_HARNESS_VALIDATION_JSON,
    CEO_DECISION_PARSER_REPORT_ONLY_RUNNER_VALIDATION_JSON,
    CEO_GATE_BLOCKER_BOARD_VALIDATION_JSON,
)


def ceo_apply_command_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_contract",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Apply Command Contract",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CONTRACT_VALIDATION_JSON,
            "count_key": "apply_command_contract_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_apply_command_contract_validation.v1",
                "contract_lane_id": "platform_engineering",
                "contract_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-contract-20260616",
                "source_packet_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-operator-apply-approval-packet-20260616",
                "apply_command_contract_count": 1,
                "command_step_count": 7,
                "guard_check_count": 10,
                "target_update_field_count": 2,
                "rollback_step_count": 4,
                "approval_granted_by_contract": False,
                "explicit_operator_apply_approval_present": False,
                "apply_command_enabled": False,
                "apply_execution_allowed": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_contract_disabled_no_mutation",
                "recommended_default": "implement_apply_command_only_after_explicit_operator_apply_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 219,
                "tasks_table_rows_after": 220,
                "task_rows_inserted_by_contract": 1,
                "lane_evidence_rows_before": 127,
                "lane_evidence_rows_after": 128,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_negative_fixtures",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Apply Command Negative Fixtures",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_NEGATIVE_FIXTURES_VALIDATION_JSON,
            "count_key": "apply_command_negative_fixture_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_apply_command_negative_fixtures_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-negative-fixtures-20260616",
                "source_contract_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-contract-20260616",
                "apply_command_negative_fixture_count": 6,
                "expected_rejection_count": 6,
                "unique_rejection_rule_count": 6,
                "apply_command_execution_count": 0,
                "approval_granted_by_fixtures": False,
                "explicit_operator_apply_approval_present": False,
                "apply_command_enabled": False,
                "apply_execution_allowed": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_negative_fixtures_ready_no_mutation",
                "recommended_default": "reject_apply_command_inputs_until_explicit_operator_apply_approval_is_validated",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 220,
                "tasks_table_rows_after": 221,
                "task_rows_inserted_by_fixture": 1,
                "lane_evidence_rows_before": 128,
                "lane_evidence_rows_after": 129,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_guard_runner",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Apply Command Guard Runner",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_GUARD_RUNNER_VALIDATION_JSON,
            "count_key": "apply_command_guard_execution_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_apply_command_guard_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-guard-runner-20260616",
                "source_fixture_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-negative-fixtures-20260616",
                "apply_command_guard_execution_count": 6,
                "rejected_fixture_count": 6,
                "accepted_fixture_count": 0,
                "matched_rejection_rule_count": 6,
                "apply_command_execution_count": 0,
                "approval_granted_by_runner": False,
                "explicit_operator_apply_approval_present": False,
                "apply_command_enabled": False,
                "apply_execution_allowed": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_guard_runner_rejected_all_no_mutation",
                "recommended_default": "keep_apply_command_disabled_until_positive_signed_operator_apply_approval_passes",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 221,
                "tasks_table_rows_after": 222,
                "task_rows_inserted_by_runner": 1,
                "lane_evidence_rows_before": 129,
                "lane_evidence_rows_after": 130,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_positive_fixture",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Apply Command Positive Fixture",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_FIXTURE_VALIDATION_JSON,
            "count_key": "positive_apply_command_fixture_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_apply_command_positive_fixture_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-fixture-20260616",
                "source_guard_runner_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-guard-runner-20260616",
                "positive_apply_command_fixture_count": 1,
                "required_field_count": 8,
                "confirmation_count": 6,
                "target_update_field_count": 2,
                "approval_granted_by_fixture": False,
                "explicit_operator_apply_approval_present": False,
                "apply_command_enabled": False,
                "apply_execution_allowed": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_positive_fixture_ready_preview_only",
                "recommended_default": "positive_apply_command_fixture_requires_report_only_runner_before_any_apply_implementation",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 222,
                "tasks_table_rows_after": 223,
                "task_rows_inserted_by_fixture": 1,
                "lane_evidence_rows_before": 130,
                "lane_evidence_rows_after": 131,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_positive_runner",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Apply Command Positive Runner",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_POSITIVE_RUNNER_VALIDATION_JSON,
            "count_key": "positive_apply_command_execution_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_apply_command_positive_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-runner-20260616",
                "source_fixture_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-fixture-20260616",
                "positive_apply_command_execution_count": 1,
                "accepted_apply_fixture_count": 1,
                "rejected_apply_fixture_count": 0,
                "preview_state_match_count": 1,
                "real_mutation_allowed_count": 0,
                "approval_granted_by_runner": False,
                "explicit_operator_apply_approval_present": False,
                "apply_command_enabled": False,
                "apply_execution_allowed": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_positive_runner_accepted_preview_only_no_mutation",
                "recommended_default": "positive_apply_runner_still_requires_explicit_real_operator_approval_before_mutation",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 223,
                "tasks_table_rows_after": 224,
                "task_rows_inserted_by_runner": 1,
                "lane_evidence_rows_before": 131,
                "lane_evidence_rows_after": 132,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_closeout",
            "label": "CEO Decision Parser Apply Readiness Signed Decision Apply Command Closeout",
            "path": CEO_DECISION_PARSER_APPLY_READINESS_SIGNED_DECISION_APPLY_COMMAND_CLOSEOUT_VALIDATION_JSON,
            "count_key": "apply_command_closeout_count",
            "expected": {
                "schema_version": "agent_company.ceo_decision_parser_apply_readiness_signed_decision_apply_command_closeout_validation.v1",
                "closeout_lane_id": "platform_engineering",
                "closeout_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-closeout-20260616",
                "source_positive_runner_task_id": "task-ceo-decision-parser-apply-readiness-signed-decision-apply-command-positive-runner-20260616",
                "apply_command_closeout_count": 1,
                "source_validation_count": 4,
                "passed_source_validation_count": 4,
                "remaining_gate_count": 5,
                "ready_for_real_mutation": False,
                "approval_granted_by_closeout": False,
                "explicit_operator_apply_approval_present": False,
                "apply_command_enabled": False,
                "apply_execution_allowed": False,
                "mutation_applied_count": 0,
                "queue_mutation_count": 0,
                "approval_request_count": 0,
                "target_status_before": "needs_review",
                "target_status_after": "needs_review",
                "local_decision": "ceo_decision_parser_apply_readiness_signed_decision_apply_command_closeout_parked_waiting_for_real_operator_approval",
                "recommended_default": "do_not_implement_or_run_mutating_apply_until_real_operator_approval_is_supplied",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 224,
                "tasks_table_rows_after": 225,
                "task_rows_inserted_by_closeout": 1,
                "lane_evidence_rows_before": 132,
                "lane_evidence_rows_after": 133,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["ceo_apply_command_integrity_specs"]
