from __future__ import annotations

from typing import Any

"""Decision intake and parser-module migration integrity specs."""

from .constants import (
    AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON,
    AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON,
    AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON,
)


def migration_decision_parser_module_integrity_specs() -> list[dict[str, Any]]:
    return [        {
            "id": "agent_company_migration_decision_parser_scaffold",
            "label": "Agent Company Migration Decision Parser Scaffold",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON,
            "count_key": "parser_scaffold_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_scaffold_validation.v1",
                "scaffold_lane_id": "platform_engineering",
                "scaffold_task_id": "task-agent-company-migration-decision-parser-scaffold-20260616",
                "source_runner_task_id": "task-agent-company-migration-decision-fixture-runner-20260616",
                "parser_scaffold_count": 1,
                "parser_stage_count": 7,
                "guard_function_count": 9,
                "accepted_decision_type_count": 4,
                "result_field_count": 8,
                "refusal_reason_count": 8,
                "fixture_coverage_count": 12,
                "local_decision": "agent_company_migration_decision_parser_scaffold_ready_for_report_only_parser_module",
                "recommended_default": "draft_report_only_parser_module_next_without_live_decision_intake",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 234,
                "tasks_table_rows_after": 235,
                "task_rows_inserted_by_parser_scaffold": 1,
                "lane_evidence_rows_before": 142,
                "lane_evidence_rows_after": 143,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "parser_module_written": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_module_draft",
            "label": "Agent Company Migration Decision Parser Module Draft",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON,
            "count_key": "parser_module_draft_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_module_draft_validation.v1",
                "module_lane_id": "platform_engineering",
                "module_task_id": "task-agent-company-migration-decision-parser-module-draft-20260616",
                "source_scaffold_task_id": "task-agent-company-migration-decision-parser-scaffold-20260616",
                "parser_module_draft_count": 1,
                "module_section_count": 8,
                "function_block_count": 9,
                "guard_function_count": 9,
                "accepted_decision_type_count": 4,
                "result_field_count": 8,
                "refusal_reason_count": 8,
                "fixture_coverage_count": 12,
                "local_decision": "agent_company_migration_decision_parser_module_draft_ready_for_report_only_module_fixtures",
                "recommended_default": "draft_report_only_module_fixture_check_next_without_installing_parser_module",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 235,
                "tasks_table_rows_after": 236,
                "task_rows_inserted_by_parser_module_draft": 1,
                "lane_evidence_rows_before": 143,
                "lane_evidence_rows_after": 144,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "parser_module_file_written": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_module_fixture_checks",
            "label": "Agent Company Migration Decision Module Fixture Checks",
            "path": AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON,
            "count_key": "module_fixture_checks_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_module_fixture_checks_validation.v1",
                "checks_lane_id": "platform_engineering",
                "checks_task_id": "task-agent-company-migration-decision-module-fixture-checks-20260616",
                "source_module_task_id": "task-agent-company-migration-decision-parser-module-draft-20260616",
                "module_fixture_checks_count": 1,
                "check_case_count": 12,
                "passed_check_count": 12,
                "failed_check_count": 0,
                "module_section_count": 8,
                "function_block_count": 9,
                "guard_function_count": 9,
                "fixture_coverage_count": 12,
                "local_decision": "agent_company_migration_decision_module_fixture_checks_ready_for_report_only_parser_module_file_draft",
                "recommended_default": "draft_report_only_parser_module_file_next_without_installing_or_live_parsing",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 236,
                "tasks_table_rows_after": 237,
                "task_rows_inserted_by_module_fixture_checks": 1,
                "lane_evidence_rows_before": 144,
                "lane_evidence_rows_after": 145,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "report_only_module_checks_executed": True,
                "parser_module_file_written": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_module_file_draft",
            "label": "Agent Company Migration Decision Parser Module File Draft",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON,
            "count_key": "parser_module_file_draft_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_module_file_draft_validation.v1",
                "file_draft_lane_id": "platform_engineering",
                "file_draft_task_id": "task-agent-company-migration-decision-parser-module-file-draft-20260616",
                "source_checks_task_id": "task-agent-company-migration-decision-module-fixture-checks-20260616",
                "parser_module_file_draft_count": 1,
                "module_source_line_count": 80,
                "guard_function_count": 9,
                "accepted_decision_type_count": 4,
                "result_field_count": 8,
                "refusal_reason_count": 8,
                "fixture_coverage_count": 12,
                "local_decision": "agent_company_migration_decision_parser_module_file_draft_ready_for_report_only_static_review",
                "recommended_default": "static_review_module_file_draft_next_without_writing_or_importing_module",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 237,
                "tasks_table_rows_after": 238,
                "task_rows_inserted_by_parser_module_file_draft": 1,
                "lane_evidence_rows_before": 145,
                "lane_evidence_rows_after": 146,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_static_review",
            "label": "Agent Company Migration Decision Parser Static Review",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON,
            "count_key": "static_review_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_static_review_validation.v1",
                "review_lane_id": "platform_engineering",
                "review_task_id": "task-agent-company-migration-decision-parser-static-review-20260616",
                "source_file_draft_task_id": "task-agent-company-migration-decision-parser-module-file-draft-20260616",
                "static_review_count": 1,
                "static_check_count": 11,
                "passed_static_check_count": 11,
                "failed_static_check_count": 0,
                "issue_count": 0,
                "recommendation_count": 5,
                "module_source_line_count": 80,
                "local_decision": "agent_company_migration_decision_parser_static_review_ready_for_report_only_install_preflight",
                "recommended_default": "draft_report_only_install_preflight_next_without_writing_or_importing_module",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 238,
                "tasks_table_rows_after": 239,
                "task_rows_inserted_by_static_review": 1,
                "lane_evidence_rows_before": 146,
                "lane_evidence_rows_after": 147,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "static_review_executed": True,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["migration_decision_parser_module_integrity_specs"]
