from __future__ import annotations

from typing import Any

"""Money-path, paid-code, and digital-product lane integrity specs."""

from .constants import (
    COMPANY_EXPANSION_GAP_MAP_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_APPROVAL_REQUEST_DRAFTS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_BUILD_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_COPY_POLISH_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_MEMO_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_DEMAND_PROOF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATED_HOLD_REGISTER_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_CHOICE_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_GATE_DECISION_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_OPERATOR_APPROVAL_BRIEF_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_APPROVAL_SIMULATION_PLAN_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_POST_POLISH_READINESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_DECISION_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_PRIVATE_REVIEW_PACKET_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISED_COMPLETENESS_VALIDATION_JSON,
    DIGITAL_PRODUCTS_LOCAL_REVISION_PASS_VALIDATION_JSON,
    FIRST_LOCAL_EVIDENCE_PACKETS_VALIDATION_JSON,
    FIRST_RANKED_MANAGER_PROOF_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PACKETS_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_PREFLIGHT_VALIDATION_JSON,
    MANAGER_PROOF_TASK_PROMOTION_QUEUE_VALIDATION_JSON,
    MONEY_PATH_COVERAGE_AUDIT_VALIDATION_JSON,
    PAID_CODE_BROWSER_REFRESH_DECISION_PACKET_VALIDATION_JSON,
    PAID_CODE_DUPLICATE_CHECK_WORKSHEET_VALIDATION_JSON,
    PAID_CODE_LOCAL_WORKSHEET_ANSWERS_VALIDATION_JSON,
)



def digital_product_asset_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "digital_products_local_asset_outline",
            "label": "Digital Products Local Asset Outline",
            "path": DIGITAL_PRODUCTS_LOCAL_ASSET_OUTLINE_VALIDATION_JSON,
            "count_key": "asset_component_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_asset_outline_validation.v1",
                "outline_lane_id": "digital_products_templates_plugins",
                "outline_task_id": "task-digital-products-local-asset-outline-20260616",
                "source_brief_task_id": "task-digital-products-local-build-brief-20260616",
                "source_brief_evidence_id": "digital-products-local-build-brief-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "asset_component_count": 6,
                "template_field_count": 10,
                "sample_template_section_count": 5,
                "blocked_by_gate_count": 4,
                "local_decision": "draft_first_template_locally_no_marketplace_or_payment_action",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 156,
                "tasks_table_rows_after": 157,
                "task_rows_inserted_by_outline": 1,
                "lane_evidence_rows_before": 79,
                "lane_evidence_rows_after": 80,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_asset_draft",
            "label": "Digital Products Local Asset Draft",
            "path": DIGITAL_PRODUCTS_LOCAL_ASSET_DRAFT_VALIDATION_JSON,
            "count_key": "draft_file_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_asset_draft_validation.v1",
                "draft_lane_id": "digital_products_templates_plugins",
                "draft_task_id": "task-digital-products-local-asset-draft-20260616",
                "source_outline_task_id": "task-digital-products-local-asset-outline-20260616",
                "source_outline_evidence_id": "digital-products-local-asset-outline-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "draft_file_count": 2,
                "positioning_answer_count": 10,
                "checklist_row_count": 9,
                "boundary_note_count": 4,
                "blocked_by_gate_count": 4,
                "local_decision": "local_draft_complete_no_marketplace_listing_or_payment_action",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 158,
                "tasks_table_rows_after": 159,
                "task_rows_inserted_by_draft": 1,
                "lane_evidence_rows_before": 80,
                "lane_evidence_rows_after": 81,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_quality_pass",
            "label": "Digital Products Local Quality Pass",
            "path": DIGITAL_PRODUCTS_LOCAL_QUALITY_PASS_VALIDATION_JSON,
            "count_key": "quality_check_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_quality_pass_validation.v1",
                "quality_lane_id": "digital_products_templates_plugins",
                "quality_task_id": "task-digital-products-local-quality-pass-20260616",
                "source_draft_task_id": "task-digital-products-local-asset-draft-20260616",
                "source_draft_evidence_id": "digital-products-local-asset-draft-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "quality_check_count": 8,
                "passed_check_count": 8,
                "revision_item_count": 5,
                "blocked_by_gate_count": 4,
                "local_decision": "quality_pass_complete_ready_for_local_packaging_no_public_action",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 160,
                "tasks_table_rows_after": 161,
                "task_rows_inserted_by_quality_pass": 1,
                "lane_evidence_rows_before": 81,
                "lane_evidence_rows_after": 82,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_packaging_manifest",
            "label": "Digital Products Local Packaging Manifest",
            "path": DIGITAL_PRODUCTS_LOCAL_PACKAGING_MANIFEST_VALIDATION_JSON,
            "count_key": "package_file_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_packaging_manifest_validation.v1",
                "manifest_lane_id": "digital_products_templates_plugins",
                "manifest_task_id": "task-digital-products-local-packaging-manifest-20260616",
                "source_quality_task_id": "task-digital-products-local-quality-pass-20260616",
                "source_quality_evidence_id": "digital-products-local-quality-pass-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "package_file_count": 6,
                "readme_section_count": 7,
                "revision_applied_count": 5,
                "blocked_by_gate_count": 4,
                "local_decision": "local_packaging_manifest_complete_no_distribution_or_payment_action",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 162,
                "tasks_table_rows_after": 163,
                "task_rows_inserted_by_manifest": 1,
                "lane_evidence_rows_before": 82,
                "lane_evidence_rows_after": 83,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_package_files",
            "label": "Digital Products Local Package Files",
            "path": DIGITAL_PRODUCTS_LOCAL_PACKAGE_FILES_VALIDATION_JSON,
            "count_key": "drafted_file_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_package_files_validation.v1",
                "files_lane_id": "digital_products_templates_plugins",
                "files_task_id": "task-digital-products-local-package-files-20260616",
                "source_manifest_task_id": "task-digital-products-local-packaging-manifest-20260616",
                "source_manifest_evidence_id": "digital-products-local-packaging-manifest-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "drafted_file_count": 4,
                "readme_section_count": 7,
                "screenshot_row_count": 6,
                "qa_row_count": 7,
                "review_prompt_count": 6,
                "blocked_by_gate_count": 4,
                "local_decision": "local_package_files_drafted_no_distribution_or_payment_action",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 164,
                "tasks_table_rows_after": 165,
                "task_rows_inserted_by_files": 1,
                "lane_evidence_rows_before": 83,
                "lane_evidence_rows_after": 84,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "digital_products_local_completeness_check",
            "label": "Digital Products Local Completeness Check",
            "path": DIGITAL_PRODUCTS_LOCAL_COMPLETENESS_CHECK_VALIDATION_JSON,
            "count_key": "completeness_check_count",
            "expected": {
                "schema_version": "agent_company.digital_products_local_completeness_check_validation.v1",
                "check_lane_id": "digital_products_templates_plugins",
                "check_task_id": "task-digital-products-local-completeness-check-20260616",
                "source_files_task_id": "task-digital-products-local-package-files-20260616",
                "source_files_evidence_id": "digital-products-local-package-files-20260616",
                "selected_candidate_id": "ai-builder-launch-checklist-pack",
                "manifest_file_count": 6,
                "drafted_file_count": 4,
                "completeness_check_count": 9,
                "passed_check_count": 9,
                "missing_file_stub_count": 2,
                "blocked_by_gate_count": 4,
                "local_decision": "local_package_complete_enough_for_private_review_no_public_action",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 166,
                "tasks_table_rows_after": 167,
                "task_rows_inserted_by_check": 1,
                "lane_evidence_rows_before": 84,
                "lane_evidence_rows_after": 85,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]
