from __future__ import annotations

from typing import Any

"""Application-packet migration integrity specs."""

from .constants import (
    AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON,
    AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON,
    AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON,
)


def migration_application_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "agent_company_migration_decision_parser_write_approval_response_application_preflight",
            "label": "Agent Company Migration Decision Parser Write Approval Response Application Preflight",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON,
            "count_key": "parser_write_approval_response_application_preflight_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_approval_response_application_preflight_validation.v1",
                "preflight_lane_id": "platform_engineering",
                "preflight_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-preflight-20260616",
                "source_review_task_id": "task-agent-company-migration-decision-parser-write-approval-response-runner-review-20260616",
                "parser_write_approval_response_application_preflight_count": 1,
                "prerequisite_check_count": 7,
                "signed_response_requirement_count": 8,
                "blocked_action_count": 12,
                "hold_condition_count": 6,
                "evidence_link_count": 4,
                "signed_response_present": False,
                "application_allowed": False,
                "local_decision": "agent_company_migration_decision_parser_write_approval_response_application_preflight_blocked_without_signed_response",
                "recommended_default": "keep_hold_until_signed_approval_response_application_packet_exists",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 254,
                "tasks_table_rows_after": 255,
                "task_rows_inserted_by_parser_write_approval_response_application_preflight": 1,
                "lane_evidence_rows_before": 162,
                "lane_evidence_rows_after": 163,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_write_approval_response_application_packet_contract",
            "label": "Agent Company Migration Decision Parser Write Approval Response Application Packet Contract",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON,
            "count_key": "parser_write_approval_response_application_packet_contract_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_approval_response_application_packet_contract_validation.v1",
                "contract_lane_id": "platform_engineering",
                "contract_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-packet-contract-20260616",
                "source_preflight_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-preflight-20260616",
                "parser_write_approval_response_application_packet_contract_count": 1,
                "application_field_count": 10,
                "eligibility_rule_count": 8,
                "blocked_action_count": 12,
                "hold_condition_count": 6,
                "evidence_link_count": 5,
                "application_allowed": False,
                "local_decision": "agent_company_migration_decision_parser_write_approval_response_application_packet_contract_ready_for_signed_packet_or_hold",
                "recommended_default": "wait_for_signed_approval_response_application_packet_without_applying",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 255,
                "tasks_table_rows_after": 256,
                "task_rows_inserted_by_parser_write_approval_response_application_packet_contract": 1,
                "lane_evidence_rows_before": 163,
                "lane_evidence_rows_after": 164,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_write_approval_response_application_packet_fixture_suite",
            "label": "Agent Company Migration Decision Parser Write Approval Response Application Packet Fixture Suite",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON,
            "count_key": "parser_write_approval_response_application_packet_fixture_suite_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_approval_response_application_packet_fixture_suite_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-packet-fixture-suite-20260616",
                "source_contract_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-packet-contract-20260616",
                "parser_write_approval_response_application_packet_fixture_suite_count": 10,
                "positive_fixture_count": 1,
                "negative_fixture_count": 9,
                "application_field_count": 10,
                "eligibility_rule_count": 8,
                "application_packet_guard_count": 10,
                "fixture_assertion_count": 10,
                "application_allowed": False,
                "local_decision": "agent_company_migration_decision_parser_write_approval_response_application_packet_fixture_suite_ready_for_report_only_runner",
                "recommended_default": "build_report_only_approval_response_application_packet_runner_next_without_applying",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 256,
                "tasks_table_rows_after": 257,
                "task_rows_inserted_by_parser_write_approval_response_application_packet_fixture_suite": 1,
                "lane_evidence_rows_before": 164,
                "lane_evidence_rows_after": 165,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "fixtures_executed": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_write_approval_response_application_packet_runner",
            "label": "Agent Company Migration Decision Parser Write Approval Response Application Packet Runner",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON,
            "count_key": "parser_write_approval_response_application_packet_runner_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_approval_response_application_packet_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-packet-runner-20260616",
                "source_fixture_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-packet-fixture-suite-20260616",
                "parser_write_approval_response_application_packet_runner_count": 1,
                "fixture_suite_count": 10,
                "fixtures_evaluated": 10,
                "accepted_result_count": 1,
                "rejected_result_count": 9,
                "passed_fixture_count": 10,
                "failed_fixture_count": 0,
                "application_packet_guard_count": 10,
                "application_allowed": False,
                "local_decision": "agent_company_migration_decision_parser_write_approval_response_application_packet_runner_ready_for_report_only_review",
                "recommended_default": "review_report_only_approval_response_application_packet_runner_results_next_without_applying",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 257,
                "tasks_table_rows_after": 258,
                "task_rows_inserted_by_parser_write_approval_response_application_packet_runner": 1,
                "lane_evidence_rows_before": 165,
                "lane_evidence_rows_after": 166,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "report_only_fixtures_evaluated": True,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_write_approval_response_application_packet_runner_review",
            "label": "Agent Company Migration Decision Parser Write Approval Response Application Packet Runner Review",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON,
            "count_key": "parser_write_approval_response_application_packet_runner_review_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_write_approval_response_application_packet_runner_review_validation.v1",
                "review_lane_id": "platform_engineering",
                "review_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-packet-runner-review-20260616",
                "source_runner_task_id": "task-agent-company-migration-decision-parser-write-approval-response-application-packet-runner-20260616",
                "parser_write_approval_response_application_packet_runner_review_count": 1,
                "runner_result_check_count": 6,
                "application_condition_count": 6,
                "hold_condition_count": 6,
                "evidence_link_count": 4,
                "operator_instruction_count": 7,
                "application_allowed": False,
                "local_decision": "agent_company_migration_decision_parser_write_approval_response_application_packet_runner_review_ready_for_signed_packet_or_hold",
                "recommended_default": "hold_without_signed_approval_response_application_packet_application",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 259,
                "tasks_table_rows_after": 260,
                "task_rows_inserted_by_parser_write_approval_response_application_packet_runner_review": 1,
                "lane_evidence_rows_before": 166,
                "lane_evidence_rows_after": 167,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["migration_application_integrity_specs"]
