from __future__ import annotations

from typing import Any

"""Parser-install migration integrity specs."""

from .constants import (
    AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON,
    AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON,
    AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON,
)


def migration_parser_install_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "agent_company_migration_decision_parser_install_preflight",
            "label": "Agent Company Migration Decision Parser Install Preflight",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON,
            "count_key": "install_preflight_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_install_preflight_validation.v1",
                "preflight_lane_id": "platform_engineering",
                "preflight_task_id": "task-agent-company-migration-decision-parser-install-preflight-20260616",
                "source_static_review_task_id": "task-agent-company-migration-decision-parser-static-review-20260616",
                "install_preflight_count": 1,
                "install_gate_count": 9,
                "preflight_check_count": 10,
                "rollback_step_count": 5,
                "approval_requirement_count": 6,
                "target_file_count": 1,
                "local_decision": "agent_company_migration_decision_parser_install_preflight_ready_for_operator_install_review",
                "recommended_default": "hold_without_operator_approval_to_write_parser_module_file",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 239,
                "tasks_table_rows_after": 240,
                "task_rows_inserted_by_install_preflight": 1,
                "lane_evidence_rows_before": 147,
                "lane_evidence_rows_after": 148,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "install_preflight_executed": True,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_install_review",
            "label": "Agent Company Migration Decision Parser Install Review",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON,
            "count_key": "install_review_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_install_review_validation.v1",
                "review_lane_id": "platform_engineering",
                "review_task_id": "task-agent-company-migration-decision-parser-install-review-20260616",
                "source_preflight_task_id": "task-agent-company-migration-decision-parser-install-preflight-20260616",
                "install_review_count": 1,
                "decision_option_count": 4,
                "approval_condition_count": 7,
                "refusal_condition_count": 7,
                "evidence_link_count": 4,
                "operator_instruction_count": 6,
                "local_decision": "agent_company_migration_decision_parser_install_review_ready_for_signed_install_decision_or_hold",
                "recommended_default": "hold_without_signed_operator_file_write_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 240,
                "tasks_table_rows_after": 241,
                "task_rows_inserted_by_install_review": 1,
                "lane_evidence_rows_before": 148,
                "lane_evidence_rows_after": 149,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_install_decision_intake_contract",
            "label": "Agent Company Migration Decision Parser Install Decision Intake Contract",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
            "count_key": "install_decision_intake_contract_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_install_decision_intake_contract_validation.v1",
                "intake_lane_id": "platform_engineering",
                "intake_task_id": "task-agent-company-migration-decision-parser-install-decision-intake-contract-20260616",
                "source_review_task_id": "task-agent-company-migration-decision-parser-install-review-20260616",
                "install_decision_intake_contract_count": 1,
                "accepted_install_decision_type_count": 4,
                "required_field_count": 8,
                "positive_fixture_count": 4,
                "negative_fixture_count": 7,
                "parser_guard_count": 8,
                "output_state_count": 4,
                "local_decision": "agent_company_migration_decision_parser_install_decision_intake_contract_ready_for_report_only_fixture_suite",
                "recommended_default": "build_report_only_install_decision_fixture_suite_next_without_applying_install_decision",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 241,
                "tasks_table_rows_after": 242,
                "task_rows_inserted_by_install_decision_intake_contract": 1,
                "lane_evidence_rows_before": 149,
                "lane_evidence_rows_after": 150,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_install_decision_fixture_suite",
            "label": "Agent Company Migration Decision Parser Install Decision Fixture Suite",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
            "count_key": "install_decision_fixture_suite_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_install_decision_fixture_suite_validation.v1",
                "fixture_lane_id": "platform_engineering",
                "fixture_task_id": "task-agent-company-migration-decision-parser-install-decision-fixture-suite-20260616",
                "source_intake_task_id": "task-agent-company-migration-decision-parser-install-decision-intake-contract-20260616",
                "install_decision_fixture_suite_count": 11,
                "positive_fixture_count": 4,
                "negative_fixture_count": 7,
                "required_field_count": 8,
                "parser_guard_count": 8,
                "output_state_count": 4,
                "fixture_assertion_count": 11,
                "local_decision": "agent_company_migration_decision_parser_install_decision_fixture_suite_ready_for_report_only_runner",
                "recommended_default": "build_report_only_install_decision_runner_next_without_applying_install_decision",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 242,
                "tasks_table_rows_after": 243,
                "task_rows_inserted_by_install_decision_fixture_suite": 1,
                "lane_evidence_rows_before": 150,
                "lane_evidence_rows_after": 151,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "fixtures_executed": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_install_decision_runner",
            "label": "Agent Company Migration Decision Parser Install Decision Runner",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON,
            "count_key": "install_decision_runner_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_install_decision_runner_validation.v1",
                "runner_lane_id": "platform_engineering",
                "runner_task_id": "task-agent-company-migration-decision-parser-install-decision-runner-20260616",
                "source_fixture_task_id": "task-agent-company-migration-decision-parser-install-decision-fixture-suite-20260616",
                "install_decision_runner_count": 1,
                "fixture_suite_count": 11,
                "fixtures_evaluated": 11,
                "accepted_result_count": 4,
                "rejected_result_count": 7,
                "passed_fixture_count": 11,
                "failed_fixture_count": 0,
                "parser_guard_count": 8,
                "output_state_count": 4,
                "local_decision": "agent_company_migration_decision_parser_install_decision_runner_ready_for_report_only_parser_static_review",
                "recommended_default": "review_report_only_runner_results_next_without_writing_or_importing_parser",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 243,
                "tasks_table_rows_after": 244,
                "task_rows_inserted_by_install_decision_runner": 1,
                "lane_evidence_rows_before": 151,
                "lane_evidence_rows_after": 152,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "report_only_fixtures_evaluated": True,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_decision_parser_install_decision_runner_review",
            "label": "Agent Company Migration Decision Parser Install Decision Runner Review",
            "path": AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
            "count_key": "install_decision_runner_review_count",
            "expected": {
                "schema_version": "agent_company.migration_decision_parser_install_decision_runner_review_validation.v1",
                "review_lane_id": "platform_engineering",
                "review_task_id": "task-agent-company-migration-decision-parser-install-decision-runner-review-20260616",
                "source_runner_task_id": "task-agent-company-migration-decision-parser-install-decision-runner-20260616",
                "install_decision_runner_review_count": 1,
                "runner_result_check_count": 6,
                "approval_condition_count": 6,
                "hold_condition_count": 6,
                "evidence_link_count": 4,
                "operator_instruction_count": 6,
                "local_decision": "agent_company_migration_decision_parser_install_decision_runner_review_ready_for_operator_parser_write_decision_or_hold",
                "recommended_default": "hold_without_signed_operator_parser_write_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 244,
                "tasks_table_rows_after": 245,
                "task_rows_inserted_by_install_decision_runner_review": 1,
                "lane_evidence_rows_before": 152,
                "lane_evidence_rows_after": 153,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_install_decision_applied": False,
                "parser_module_file_written": False,
                "parser_module_imported": False,
                "live_decisions_parsed": False,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["migration_parser_install_integrity_specs"]
