from __future__ import annotations

"""Compatibility facade for service-worker control-plane helpers and writers."""

from .service_worker_utils import (
    load_report_json_or_error,
    check_expected_values,
    db_scalar,
    service_worker_chain_db_snapshot,
)

from .service_worker_core import (
    SERVICE_WORKER_REQUIRED_FIELDS,
    SERVICE_WORKER_TYPES,
    service_worker_type_for_request,
    service_worker_objective,
    service_worker_allowed_actions,
    service_worker_stop_conditions,
    service_worker_boundaries,
    service_worker_data_boundary,
    service_worker_expected_output,
    service_worker_packet_path,
    synthesize_service_worker_request,
    validate_service_worker_request_object,
    latest_approval_for_request,
    approval_not_expired,
    service_worker_readiness_entry,
    write_service_worker_execution_readiness,
)

from .service_worker_scope import (
    SIDE_EFFECT_SCOPE_RULES,
    NEGATION_MARKERS,
    normalized_scope_text,
    term_present_with_negation_awareness,
    denial_present,
    positive_conflicts,
    concrete_hosts_from_packet,
    host_scope_mentions,
    service_worker_scope_diff_entry,
    write_service_worker_scope_diff,
    compact_sequence,
    scope_template_output_paths,
    scope_template_hosts,
    scope_template_starting_urls,
    scope_template_allowed_data,
    scope_template_required_denials,
    join_scope_items,
    service_worker_scope_template_entry,
    write_service_worker_scope_templates,
    service_worker_approval_review_entry,
    write_service_worker_approval_review,
)

from .service_worker_assignment import (
    WORKER_TYPE_ASSIGNMENT_ROLES,
    lane_manager_for_row,
    service_worker_assignment_plan_entry,
    write_service_worker_assignment_plan,
    service_worker_pool_registry_entries,
    write_service_worker_pool_registry,
    service_worker_pool_registration_department,
    service_worker_pool_registration_boundaries,
    service_worker_pool_registration_entry,
    write_service_worker_pool_registration_plan,
    service_worker_gate_map_entry,
    write_service_worker_gate_map,
)

from .service_worker_decisions import (
    service_worker_human_decision_packet_rows,
    write_service_worker_human_decision_packets,
    service_worker_post_decision_simulation_rows,
    write_service_worker_post_decision_simulation,
    service_worker_post_decision_refresh_plan_rows,
    write_service_worker_post_decision_refresh_plan,
    service_worker_decision_drift_rows,
    write_service_worker_decision_drift_guard,
    service_worker_decision_command_safety_rows,
    write_service_worker_decision_command_safety,
    service_worker_decision_authority_for_packet,
    service_worker_decision_authority_matrix_rows,
    write_service_worker_decision_authority_matrix,
    service_worker_decision_preflight_rows,
    write_service_worker_decision_preflight,
)

from .service_worker_queue import (
    write_service_worker_queue,
    service_worker_dequeue_route,
    service_worker_dequeue_result_paths,
    write_service_worker_dequeue_plan,
)

__all__ = [
    "load_report_json_or_error",
    "check_expected_values",
    "db_scalar",
    "service_worker_chain_db_snapshot",
    "SERVICE_WORKER_REQUIRED_FIELDS",
    "SERVICE_WORKER_TYPES",
    "service_worker_type_for_request",
    "service_worker_objective",
    "service_worker_allowed_actions",
    "service_worker_stop_conditions",
    "service_worker_boundaries",
    "service_worker_data_boundary",
    "service_worker_expected_output",
    "service_worker_packet_path",
    "synthesize_service_worker_request",
    "validate_service_worker_request_object",
    "latest_approval_for_request",
    "approval_not_expired",
    "service_worker_readiness_entry",
    "write_service_worker_execution_readiness",
    "SIDE_EFFECT_SCOPE_RULES",
    "NEGATION_MARKERS",
    "normalized_scope_text",
    "term_present_with_negation_awareness",
    "denial_present",
    "positive_conflicts",
    "concrete_hosts_from_packet",
    "host_scope_mentions",
    "service_worker_scope_diff_entry",
    "write_service_worker_scope_diff",
    "compact_sequence",
    "scope_template_output_paths",
    "scope_template_hosts",
    "scope_template_starting_urls",
    "scope_template_allowed_data",
    "scope_template_required_denials",
    "join_scope_items",
    "service_worker_scope_template_entry",
    "write_service_worker_scope_templates",
    "service_worker_approval_review_entry",
    "write_service_worker_approval_review",
    "WORKER_TYPE_ASSIGNMENT_ROLES",
    "lane_manager_for_row",
    "service_worker_assignment_plan_entry",
    "write_service_worker_assignment_plan",
    "service_worker_pool_registry_entries",
    "write_service_worker_pool_registry",
    "service_worker_pool_registration_department",
    "service_worker_pool_registration_boundaries",
    "service_worker_pool_registration_entry",
    "write_service_worker_pool_registration_plan",
    "service_worker_gate_map_entry",
    "write_service_worker_gate_map",
    "service_worker_human_decision_packet_rows",
    "write_service_worker_human_decision_packets",
    "service_worker_post_decision_simulation_rows",
    "write_service_worker_post_decision_simulation",
    "service_worker_post_decision_refresh_plan_rows",
    "write_service_worker_post_decision_refresh_plan",
    "service_worker_decision_drift_rows",
    "write_service_worker_decision_drift_guard",
    "service_worker_decision_command_safety_rows",
    "write_service_worker_decision_command_safety",
    "service_worker_decision_authority_for_packet",
    "service_worker_decision_authority_matrix_rows",
    "write_service_worker_decision_authority_matrix",
    "service_worker_decision_preflight_rows",
    "write_service_worker_decision_preflight",
    "write_service_worker_queue",
    "service_worker_dequeue_route",
    "service_worker_dequeue_result_paths",
    "write_service_worker_dequeue_plan",
]
