from __future__ import annotations

from typing import Any

"""Foundation, apply-preflight, and operator-review migration integrity specs."""

from .constants import (
    AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON,
    AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON,
    AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_MODULE_FIXTURE_CHECKS_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_INSTALL_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_MODULE_FILE_DRAFT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_SCAFFOLD_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_STATIC_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_REQUEST_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PACKET_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_APPLICATION_PREFLIGHT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_APPROVAL_RESPONSE_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_FIXTURE_SUITE_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_INTAKE_CONTRACT_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_DECISION_PARSER_WRITE_DECISION_RUNNER_VALIDATION_JSON,
    AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON,
    AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON,
)


def migration_foundation_integrity_specs() -> list[dict[str, Any]]:
    return [
        {
            "id": "agent_company_infrastructure_radar",
            "label": "Agent Company Infrastructure Radar",
            "path": AGENT_COMPANY_INFRASTRUCTURE_RADAR_VALIDATION_JSON,
            "count_key": "infrastructure_radar_count",
            "expected": {
                "schema_version": "agent_company.infrastructure_radar_validation.v1",
                "radar_lane_id": "platform_engineering",
                "radar_task_id": "task-agent-company-infrastructure-radar-20260616",
                "infrastructure_radar_count": 1,
                "primary_source_count": 5,
                "candidate_count": 5,
                "architecture_mapping_count": 7,
                "recommended_spine_count": 4,
                "cashflow_lane_mapping_count": 8,
                "approval_gate_count": 6,
                "local_decision": "agent_company_infrastructure_radar_ready_for_department_design",
                "recommended_default": "use_temporal_or_durable_queue_for_workflow_state_and_agent_frameworks_for_role_level_reasoning",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 225,
                "tasks_table_rows_after": 226,
                "task_rows_inserted_by_radar": 1,
                "lane_evidence_rows_before": 133,
                "lane_evidence_rows_after": 134,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_department_architecture_packet",
            "label": "Agent Company Department Architecture Packet",
            "path": AGENT_COMPANY_DEPARTMENT_ARCHITECTURE_PACKET_VALIDATION_JSON,
            "count_key": "department_architecture_packet_count",
            "expected": {
                "schema_version": "agent_company.department_architecture_packet_validation.v1",
                "packet_lane_id": "platform_engineering",
                "packet_task_id": "task-agent-company-department-architecture-packet-20260616",
                "source_radar_task_id": "task-agent-company-infrastructure-radar-20260616",
                "department_architecture_packet_count": 1,
                "department_count": 7,
                "table_blueprint_count": 10,
                "service_request_type_count": 12,
                "thread_template_count": 8,
                "worker_pool_interface_count": 7,
                "approval_gate_count": 6,
                "local_decision": "agent_company_department_architecture_packet_ready_for_schema_plan",
                "recommended_default": "materialize_schema_plan_next_without_starting_workers_or_external_actions",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 226,
                "tasks_table_rows_after": 227,
                "task_rows_inserted_by_packet": 1,
                "lane_evidence_rows_before": 134,
                "lane_evidence_rows_after": 135,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_department_schema_plan",
            "label": "Agent Company Department Schema Plan",
            "path": AGENT_COMPANY_DEPARTMENT_SCHEMA_PLAN_VALIDATION_JSON,
            "count_key": "schema_plan_count",
            "expected": {
                "schema_version": "agent_company.department_schema_plan_validation.v1",
                "schema_plan_lane_id": "platform_engineering",
                "schema_plan_task_id": "task-agent-company-department-schema-plan-20260616",
                "source_packet_task_id": "task-agent-company-department-architecture-packet-20260616",
                "schema_plan_count": 1,
                "table_plan_count": 10,
                "column_plan_count": 127,
                "index_plan_count": 20,
                "service_request_contract_count": 12,
                "migration_step_count": 8,
                "guardrail_count": 8,
                "local_decision": "agent_company_department_schema_plan_ready_for_report_only_migration_draft",
                "recommended_default": "draft_report_only_migration_next_without_creating_tables_or_workers",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 227,
                "tasks_table_rows_after": 228,
                "task_rows_inserted_by_schema_plan": 1,
                "lane_evidence_rows_before": 135,
                "lane_evidence_rows_after": 136,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_report_only_migration_draft",
            "label": "Agent Company Report-Only Migration Draft",
            "path": AGENT_COMPANY_REPORT_ONLY_MIGRATION_DRAFT_VALIDATION_JSON,
            "count_key": "migration_draft_count",
            "expected": {
                "schema_version": "agent_company.report_only_migration_draft_validation.v1",
                "migration_lane_id": "platform_engineering",
                "migration_task_id": "task-agent-company-report-only-migration-draft-20260616",
                "source_schema_plan_task_id": "task-agent-company-department-schema-plan-20260616",
                "migration_draft_count": 1,
                "table_migration_count": 10,
                "create_statement_count": 10,
                "index_statement_count": 20,
                "validation_query_count": 10,
                "rollback_statement_count": 30,
                "apply_gate_count": 7,
                "local_decision": "agent_company_report_only_migration_draft_ready_for_apply_preflight_packet",
                "recommended_default": "draft_apply_preflight_next_without_executing_migration_sql",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 228,
                "tasks_table_rows_after": 229,
                "task_rows_inserted_by_migration_draft": 1,
                "lane_evidence_rows_before": 136,
                "lane_evidence_rows_after": 137,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "migration_sql_executed": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_apply_preflight",
            "label": "Agent Company Migration Apply Preflight",
            "path": AGENT_COMPANY_MIGRATION_APPLY_PREFLIGHT_VALIDATION_JSON,
            "count_key": "preflight_packet_count",
            "expected": {
                "schema_version": "agent_company.migration_apply_preflight_validation.v1",
                "preflight_lane_id": "platform_engineering",
                "preflight_task_id": "task-agent-company-migration-apply-preflight-20260616",
                "source_migration_task_id": "task-agent-company-report-only-migration-draft-20260616",
                "preflight_packet_count": 1,
                "preflight_check_count": 9,
                "operator_gate_count": 7,
                "dry_run_step_count": 8,
                "apply_command_contract_count": 1,
                "rollback_drill_count": 3,
                "local_decision": "agent_company_migration_apply_preflight_ready_for_operator_review_packet",
                "recommended_default": "prepare_operator_review_next_without_running_apply_command",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 229,
                "tasks_table_rows_after": 230,
                "task_rows_inserted_by_preflight": 1,
                "lane_evidence_rows_before": 137,
                "lane_evidence_rows_after": 138,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
        {
            "id": "agent_company_migration_operator_review",
            "label": "Agent Company Migration Operator Review",
            "path": AGENT_COMPANY_MIGRATION_OPERATOR_REVIEW_VALIDATION_JSON,
            "count_key": "operator_review_packet_count",
            "expected": {
                "schema_version": "agent_company.migration_operator_review_validation.v1",
                "review_lane_id": "platform_engineering",
                "review_task_id": "task-agent-company-migration-operator-review-20260616",
                "source_preflight_task_id": "task-agent-company-migration-apply-preflight-20260616",
                "operator_review_packet_count": 1,
                "decision_option_count": 4,
                "approval_condition_count": 8,
                "refusal_condition_count": 8,
                "human_instruction_count": 7,
                "evidence_link_count": 4,
                "local_decision": "agent_company_migration_operator_review_packet_ready_for_signed_decision_or_hold",
                "recommended_default": "hold_without_signed_operator_approval",
                "live_tasks_created": 1,
                "live_tasks_completed": 1,
                "tasks_table_rows_before": 230,
                "tasks_table_rows_after": 231,
                "task_rows_inserted_by_review": 1,
                "lane_evidence_rows_before": 138,
                "lane_evidence_rows_after": 139,
                "evidence_rows_inserted_or_updated": 1,
                "all_checks_passed": True,
                "failure_count": 0,
                "operator_decision_applied": False,
                "migration_sql_executed": False,
                "apply_command_enabled": False,
                "tables_created": 0,
                "browser_sessions_started": 0,
                "account_actions": False,
                "wallet_actions": False,
                "payment_actions": False,
                "public_actions": False,
                "security_testing_actions": False,
                "real_money_actions": False,
                "service_requests_updated": 0,
                "service_requests_assigned": 0,
                "worker_starts": 0,
                "api_calls": False,
                "external_side_effects": False,
            },
        },
    ]


__all__ = ["migration_foundation_integrity_specs"]
