#!/usr/bin/env python3
"""2026-06-19 recent UI unlock catalog segment: afternoon."""

from __future__ import annotations

RECENT_UI_UNLOCKS_20260619_AFTERNOON = [{'task_id': 'task-agent-company-atlas-command-cockpit-signal-rails-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_signal_rails_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-signal-rails-v1-20260619',
  'title': 'Command Cockpit Signal Rails',
  'time_task': '2026-06-19T10:34:28Z',
  'time_trace': '2026-06-19T10:34:20Z',
  'priority': 152,
  'task_summary': 'Compress mounted-stage objective and bot docks into slim signal rails inside the Command '
                  'Cockpit.',
  'trace_summary': 'Scoped the Cockpit Objective and Bot Party docks into compact rails with hidden long copy, '
                   'smaller cells, and bot avatar pips so the selected lane keeps status and presence without '
                   'crowding the playable stage.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-signal-rails-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-holo-floor-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_holo_floor_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-holo-floor-v1-20260619',
  'title': 'Command Cockpit Holo Floor',
  'time_task': '2026-06-19T10:18:28Z',
  'time_trace': '2026-06-19T10:18:20Z',
  'priority': 151,
  'task_summary': 'Turn the selected-lane holo board into a lower perspective floor inside the Command '
                  'Cockpit.',
  'trace_summary': 'Scoped the existing state-driven holo board into a thinner perspective floor with drifting '
                   'grid motion, a faster runner, and compact nodes so the selected lane reads like a playable '
                   'board without adding scroll height.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-holo-floor-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-control-matrix-quick-deck-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_control_matrix_quick_deck_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-control-matrix-quick-deck-v1-20260619',
  'title': 'Command Cockpit Control Matrix Quick Deck',
  'time_task': '2026-06-19T10:02:28Z',
  'time_trace': '2026-06-19T10:02:20Z',
  'priority': 150,
  'task_summary': 'Compress the selected-lane control matrix into a quick game-controller deck inside the '
                  'Command Cockpit.',
  'trace_summary': 'Scoped the Cockpit control matrix into three compact rows: micro chronicle chips, view '
                   'portals, and a shared transition plus lane-switch row so more of the playable mounted '
                   'stage remains visible.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-control-matrix-quick-deck-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-viewport-lock-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_viewport_lock_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-viewport-lock-v1-20260619',
  'title': 'Command Cockpit Viewport Lock',
  'time_task': '2026-06-19T09:46:28Z',
  'time_trace': '2026-06-19T09:46:20Z',
  'priority': 149,
  'task_summary': 'Lock the Command Cockpit selected-lane surface into a bounded one-screen stack.',
  'trace_summary': 'Scoped the Cockpit detail panel to a fixed-height stack, moved scrolling into the mounted '
                   'stage, and added an animated runner to the active Overview module button.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-viewport-lock-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-quest-tile-compression-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_quest_tile_compression_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-quest-tile-compression-v1-20260619',
  'title': 'Command Cockpit Quest Tile Compression',
  'time_task': '2026-06-19T09:30:28Z',
  'time_trace': '2026-06-19T09:30:20Z',
  'priority': 148,
  'task_summary': 'Compress the default quest hero tile inside the Command Cockpit Overview module.',
  'trace_summary': 'Scoped the Quest cockpit tile to smaller portrait and meter sockets, tighter padding, and '
                   'one-line objective copy so the first Overview module feels like a dense game card.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-quest-tile-compression-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-overview-module-compression-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_overview_module_compression_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-overview-module-compression-v1-20260619',
  'title': 'Command Cockpit Overview Module Compression',
  'time_task': '2026-06-19T09:14:28Z',
  'time_trace': '2026-06-19T09:14:20Z',
  'priority': 147,
  'task_summary': 'Compress the default Overview mission module inside the Command Cockpit mounted stage.',
  'trace_summary': 'Scoped the Overview dock, meter, module buttons, and Overview detail-section spacing to a '
                   'denser Command Cockpit treatment so the first selected-lane module reads like a compact '
                   'mission board.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-overview-module-compression-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-mounted-stage-expansion-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_mounted_stage_expansion_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-mounted-stage-expansion-v1-20260619',
  'title': 'Command Cockpit Mounted Stage Expansion',
  'time_task': '2026-06-19T08:58:28Z',
  'time_trace': '2026-06-19T08:58:20Z',
  'priority': 146,
  'task_summary': 'Spend reclaimed Cockpit chrome space on a taller playable mounted lane stage.',
  'trace_summary': 'Expanded the Command Cockpit mounted stage, trimmed its padding and bottom fade, and '
                   'flushed the first detail section so more selected-lane work appears before internal '
                   'scrolling.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-mounted-stage-expansion-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-stage-lens-compression-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_stage_lens_compression_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-stage-lens-compression-v1-20260619',
  'title': 'Command Cockpit Stage Lens Compression',
  'time_task': '2026-06-19T08:42:28Z',
  'time_trace': '2026-06-19T08:42:20Z',
  'priority': 145,
  'task_summary': 'Slim the mounted stage lens inside the Command Cockpit so the playable lane surface begins '
                  'sooner.',
  'trace_summary': 'Scoped the sticky stage lens to a thinner Cockpit strip with tighter columns, hidden meta '
                   'copy, and denser signal cells while preserving the full lens elsewhere.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-stage-lens-compression-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-hud-compression-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_hud_compression_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-hud-compression-v1-20260619',
  'title': 'Command Cockpit HUD Compression',
  'time_task': '2026-06-19T08:26:28Z',
  'time_trace': '2026-06-19T08:26:20Z',
  'priority': 144,
  'task_summary': 'Compress the selected-lane HUD into a denser status bar inside the Command Cockpit.',
  'trace_summary': 'Scoped the active-lane HUD to tighter Cockpit dimensions, smaller portraits and meters, '
                   'denser stat cells, and hidden long HUD subcopy so the mounted lane stage starts sooner.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-hud-compression-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-lane-selector-compression-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_lane_selector_compression_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-lane-selector-compression-v1-20260619',
  'title': 'Command Cockpit Lane Selector Compression',
  'time_task': '2026-06-19T08:10:28Z',
  'time_trace': '2026-06-19T08:10:20Z',
  'priority': 143,
  'task_summary': 'Let the new level selector replace duplicate lane rail chrome inside the Command Cockpit.',
  'trace_summary': 'Compressed Cockpit lane cards with smaller avatars and selector cells, then hid redundant '
                   'progress bars and muted summaries so more money-path levels fit before scrolling.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-lane-selector-compression-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-lane-rail-level-selector-v1-20260619',
  'trace_id': 'trace-atlas_lane_rail_level_selector_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-lane-rail-level-selector-v1-20260619',
  'title': 'Lane Rail Level Selector',
  'time_task': '2026-06-19T07:54:28Z',
  'time_trace': '2026-06-19T07:54:20Z',
  'priority': 142,
  'task_summary': 'Make the lane rail read like a compact playable level selector instead of a task-card list.',
  'trace_summary': 'Added a four-cell level selector tray to each lane rail card for level, XP, gates, wins, '
                   'and live work, with scoped sweep motion and reduced-motion fallback.',
  'artifact': 'reports/agent-company-atlas-lane-rail-level-selector-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-cockpit-stage-gate-v1-20260619',
  'trace_id': 'trace-atlas_command_cockpit_stage_gate_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-cockpit-stage-gate-v1-20260619',
  'title': 'Command Cockpit Stage Gate',
  'time_task': '2026-06-19T07:38:28Z',
  'time_trace': '2026-06-19T07:38:20Z',
  'priority': 141,
  'task_summary': 'Separate the Command Cockpit from the tactical Map so the selected lane opens as one '
                  'focused stage.',
  'trace_summary': 'The Cockpit stage now hides the atlas map, uses a two-column lane rail plus detail layout, '
                   'and keeps the map available as its own teleport level to reduce first-screen command '
                   'clutter.',
  'artifact': 'reports/agent-company-atlas-command-cockpit-stage-gate-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-bot-card-deck-v1-20260619',
  'trace_id': 'trace-atlas_command_bot_card_deck_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-bot-card-deck-v1-20260619',
  'title': 'Command Bot Card Deck',
  'time_task': '2026-06-19T07:22:28Z',
  'time_trace': '2026-06-19T07:22:20Z',
  'priority': 140,
  'task_summary': 'Make the Bots command-room cards denser so more live bot controls appear before scrolling.',
  'trace_summary': 'Compressed Bots-stage command cards with smaller summary chips, portraits, stat tiles, '
                   'hidden long ask/thread copy, and wider command buttons for faster command-room scanning.',
  'artifact': 'reports/agent-company-atlas-command-bot-card-deck-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-bot-command-room-v1-20260619',
  'trace_id': 'trace-atlas_command_bot_command_room_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-bot-command-room-v1-20260619',
  'title': 'Command Bot Command Room',
  'time_task': '2026-06-19T07:06:28Z',
  'time_trace': '2026-06-19T07:06:20Z',
  'priority': 139,
  'task_summary': 'Make the Bots teleport open as a focused bot command room instead of a generic support '
                  'archive stack.',
  'trace_summary': 'Compacted the Bots support dock, expanded the bot command panel into a taller bounded '
                   'stage, and made bot status chips sticky while scanning the command matrix.',
  'artifact': 'reports/agent-company-atlas-command-bot-command-room-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-map-overlay-dock-v1-20260619',
  'trace_id': 'trace-atlas_command_map_overlay_dock_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-map-overlay-dock-v1-20260619',
  'title': 'Command Map Overlay Dock',
  'time_task': '2026-06-19T06:50:28Z',
  'time_trace': '2026-06-19T06:50:20Z',
  'priority': 138,
  'task_summary': 'Reduce Map stage overlay occlusion so the solo atlas board stays visible while context '
                  'remains readable.',
  'trace_summary': 'Compressed the Map stage playback and lane-focus overlays into compact HUD strips, hiding '
                   'long copy and preserving selected path stats without covering the playable atlas board.',
  'artifact': 'reports/agent-company-atlas-command-map-overlay-dock-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-map-solo-fill-v1-20260619',
  'trace_id': 'trace-atlas_command_map_solo_fill_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-map-solo-fill-v1-20260619',
  'title': 'Command Map Solo Fill',
  'time_task': '2026-06-19T06:34:28Z',
  'time_trace': '2026-06-19T06:34:20Z',
  'priority': 137,
  'task_summary': 'Make the solo Map stage fill like a playable level map instead of leaving a small world in '
                  'a tall board.',
  'trace_summary': 'Adjusted solo map reset zoom, added an animated grid underlay, and boosted route glow so '
                   'the Map teleport opens a denser game-like atlas surface.',
  'artifact': 'reports/agent-company-atlas-command-map-solo-fill-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-command-map-stage-solo-v1-20260619',
  'trace_id': 'trace-atlas_command_map_stage_solo_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-command-map-stage-solo-v1-20260619',
  'title': 'Command Map Stage Solo',
  'time_task': '2026-06-19T06:18:28Z',
  'time_trace': '2026-06-19T06:18:20Z',
  'priority': 136,
  'task_summary': 'Make the Map teleport open a dedicated map stage instead of the full cockpit grid.',
  'trace_summary': 'Added command map solo layout so the Map stage hides lane/detail columns and expands the '
                   'atlas map across the bounded command surface.',
  'artifact': 'reports/agent-company-atlas-command-map-stage-solo-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-stage-focus-v1-20260619',
  'trace_id': 'trace-atlas_stage_focus_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-stage-focus-v1-20260619',
  'title': 'Atlas Stage Focus',
  'time_task': '2026-06-19T06:02:28Z',
  'time_trace': '2026-06-19T06:02:20Z',
  'priority': 135,
  'task_summary': 'Turn the teleport rail into a true stage selector so normal decks stop rendering unrelated '
                  'panel stacks.',
  'trace_summary': 'Added atlasStage routing, section stage tags, and focus gates so Cockpit, Map, Bots, Feed, '
                   'Worlds, and Assets each reveal their matching stage while All remains the full audit '
                   'stack.',
  'artifact': 'reports/agent-company-atlas-stage-focus-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-deck-stage-frame-glow-v1-20260619',
  'trace_id': 'trace-atlas_deck_stage_frame_glow_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-deck-stage-frame-glow-v1-20260619',
  'title': 'Deck Stage Frame Glow',
  'time_task': '2026-06-19T05:44:28Z',
  'time_trace': '2026-06-19T05:44:20Z',
  'priority': 134,
  'task_summary': 'Make compressed deck panels feel more like premium live game stages instead of plain scroll '
                  'boxes.',
  'trace_summary': 'Added sticky scanline and glow chrome to bounded deck stages, preserving the All deck as a '
                   'clean full audit view.',
  'artifact': 'reports/agent-company-atlas-deck-stage-frame-glow-trace-metadata-20260619.json'},
 {'task_id': 'task-agent-company-atlas-deck-stage-compression-v1-20260619',
  'trace_id': 'trace-atlas_deck_stage_compression_added-20260619',
  'trace_meta_id': 'trace-agent-company-atlas-deck-stage-compression-v1-20260619',
  'title': 'Deck Stage Compression',
  'time_task': '2026-06-19T05:28:28Z',
  'time_trace': '2026-06-19T05:28:20Z',
  'priority': 133,
  'task_summary': 'Reduce whole-page scroll height by turning each normal deck into a bounded stage surface.',
  'trace_summary': 'Bounded non-audit deck sections with internal scroll, stable scrollbars, and snap points '
                   'while preserving the All deck as the full expandable audit view.',
  'artifact': 'reports/agent-company-atlas-deck-stage-compression-trace-metadata-20260619.json'}]
